openapi: 3.1.0
info:
  title: sui_multiGetTransactionBlocks
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - sui_multiGetTransactionBlocks
      description: |
        Returns an ordered list of transaction responses. The method will throw an error if the input contains any duplicate or the input size exceeds QUERY_MAX_RESULT_LIMIT
      summary: sui_multiGetTransactionBlocks
      operationId: sui-sui_multiGetTransactionBlocks
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: sui_multiGetTransactionBlocks
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  items:
                    oneOf:
                      - title: digests
                        type: array
                        items:
                          $ref: "../components/schemas/TransactionDigest.yaml"
                        description: A list of transaction digests.
                      - title: options
                        $ref: "../components/schemas/TransactionBlockResponseOptions.yaml"
                        description: Config options to control which fields to fetch
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "sui_multiGetTransactionBlocks",
                  "params":
                    [
                      [
                        "EMqJqkQip6UaTkdff493ewAQNHGQFJwXDDn6m9CTgZzo",
                        "Hn3B25vTQNTFAdThFkWvfkiAAUZxzwTaj4uEengu1ACX",
                        "9vLSG9a4QcLcMdG1xCu6FRdXAjWWqvJHoHBCJfPMKkR9",
                      ],
                      {
                        "showInput": true,
                        "showRawInput": false,
                        "showEffects": true,
                        "showEvents": true,
                        "showObjectChanges": false,
                        "showBalanceChanges": false,
                        "showRawEffects": false,
                      },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    type: array
                    items:
                      $ref: "../components/schemas/TransactionBlockResponse.yaml"
              example:
                $ref: "../components/examples/sui_multiGetTransactionBlocks.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
