openapi: 3.1.0
info:
  title: sui_getCheckpoints
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - sui_getCheckpoints
      description: |
        Return paginated list of checkpoints
      summary: sui_getCheckpoints
      operationId: sui-sui_getCheckpoints
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: sui_getCheckpoints
                params:
                  type: array
                  minItems: 1
                  maxItems: 3
                  items:
                    oneOf:
                      - title: cursor
                        $ref: "../components/schemas/BigInt_for_uint64.yaml"
                        description: An optional paging cursor. If provided, the query will start from the next item after the specified cursor. Default to start from the first item if not specified.
                      - title: limit
                        type: integer
                        description: Maximum item returned per page, default to [QUERY_MAX_RESULT_LIMIT_CHECKPOINTS] if not specified.
                      - title: descending_order
                        type: boolean
                        description: Query result ordering, default to false (ascending order), oldest record first.
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "sui_getCheckpoints",
                  "params": ["1004", 4, false],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    $ref: "../components/schemas/Page_for_Checkpoint_and_BigInt_for_uint64.yaml"
              example:
                $ref: "../components/examples/sui_getCheckpoints.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
