openapi: 3.1.0
info:
  title: sui_getNormalizedMoveModule
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - sui_getNormalizedMoveModule
      description: |
        Return a structured representation of Move module
      summary: sui_getNormalizedMoveModule
      operationId: sui-sui_getNormalizedMoveModule
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: sui_getNormalizedMoveModule
                params:
                  type: array
                  minItems: 2
                  maxItems: 2
                  items:
                    oneOf:
                      - title: package
                        $ref: "../components/schemas/ObjectID.yaml"
                        description: The package ID
                      - title: module_name
                        type: string
                        description: The module name
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "sui_getNormalizedMoveModule",
                  "params":
                    [
                      "0x0047d5fa0a823e7d0ff4d55c32b09995a0ae1eedfee9c7b1354e805ed10ee3d0",
                      "module",
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    $ref: "../components/schemas/SuiMoveNormalizedModule.yaml"
              example:
                $ref: "../components/examples/sui_getNormalizedMoveModule.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
