openapi: 3.1.0
info:
  title: sui_getProtocolConfig
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - sui_getProtocolConfig
      description: |
        Return the protocol config table for the given version number. If the version number is not specified, If none is specified, the node uses the version of the latest epoch it has processed.
      summary: sui_getProtocolConfig
      operationId: sui-sui_getProtocolConfig
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: sui_getProtocolConfig
                params:
                  type: array
                  minItems: 0
                  maxItems: 1
                  items:
                    oneOf:
                      - title: version
                        $ref: "../components/schemas/BigInt_for_uint64.yaml"
                        description: An optional protocol version specifier. If omitted, the latest protocol config table for the node will be returned.
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "sui_getProtocolConfig",
                  "params": [6],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    $ref: "../components/schemas/ProtocolConfig.yaml"
              example:
                $ref: "../components/examples/sui_getProtocolConfig.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
