openapi: 3.1.0
info:
  title: suix_getBalance
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - suix_getBalance
      description: |
        Return the total coin balance for one coin type, owned by the address owner.
      summary: suix_getBalance
      operationId: sui-suix_getBalance
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: suix_getBalance
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  items:
                    oneOf:
                      - title: owner
                        $ref: "../components/schemas/SuiAddress.yaml"
                        description: The owner's Sui address
                      - title: coin_type
                        type: string
                        description: Optional type names for the coin (e.g., 0x168da5bf1f48dafc111b0a488fa454aca95e0b5e::usdc::USDC), default to 0x2::sui::SUI if not specified.
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "suix_getBalance",
                  "params":
                    [
                      "0xa6f5a7953a75dc632e696cabe60560522a017bf2fb0bd930d1ec22c06f1ee4e4",
                      "0x168da5bf1f48dafc111b0a488fa454aca95e0b5e::usdc::USDC",
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  result:
                    $ref: "../components/schemas/Balance.yaml"
              example:
                $ref: "../components/examples/suix_getBalance.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
