openapi: 3.1.0
info:
  title: suix_getCoins
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - suix_getCoins
      description: |
        Return all Coin<`coin_type`> objects owned by an address.
      summary: suix_getCoins
      operationId: sui-suix_getCoins
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: suix_getCoins
                params:
                  type: array
                  minItems: 1
                  maxItems: 4
                  items:
                    oneOf:
                      - title: owner
                        $ref: "../components/schemas/SuiAddress.yaml"
                        description: The owner's Sui address
                      - title: coin_type
                        type: string
                        description: Optional type name for the coin (e.g., 0x168da5bf1f48dafc111b0a488fa454aca95e0b5e::usdc::USDC), default to 0x2::sui::SUI if not specified.
                      - title: cursor
                        type: string
                        description: Optional paging cursor
                      - title: limit
                        type: integer
                        description: Maximum number of items per page
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "suix_getCoins",
                  "params":
                    [
                      "0x6d907beaa3a49db57bdfdb3557e6d405cbf01c293a53e01457d65e92b5d8dd68",
                      "0x2::sui::SUI",
                      "0xee6b5173afedb35330f60397c2cbb48196ba41921246c304be7b490cee0904eb",
                      3,
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  jsonrpc:
                    type: string
                  result:
                    $ref: "../components/schemas/Page_for_Coin_and_String.yaml"
              example:
                $ref: "../components/examples/suix_getCoins.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
