openapi: 3.1.0
info:
  title: suix_resolveNameServiceNames
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - suix_resolveNameServiceNames
      description: |
        Return the resolved names given address, if multiple names are resolved, the first one is the primary name.
      summary: suix_resolveNameServiceNames
      operationId: sui-suix_resolveNameServiceNames
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: suix_resolveNameServiceNames
                params:
                  type: array
                  minItems: 1
                  maxItems: 3
                  items:
                    oneOf:
                      - title: address
                        $ref: "../components/schemas/SuiAddress.yaml"
                        description: The address to resolve
                      - title: cursor
                        $ref: "../components/schemas/ObjectID.yaml"
                        description: Optional paging cursor
                      - title: limit
                        type: integer
                        description: Maximum number of items per page
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "suix_resolveNameServiceNames",
                  "params":
                    [
                      "0x5cd6fa76ed1d18f05f15e35075252ddec4fb83621d55952d9172fcfcb72feae2",
                      "0xd22bbb46f892c42d9ec0ae4de93e02c75973a51c17180798237326a58694a2cf",
                      3,
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    $ref: "../components/schemas/Page_for_String_and_ObjectID.yaml"
              example:
                $ref: "../components/examples/suix_resolveNameServiceNames.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
