openapi: 3.1.0
info:
  title: suix_getStakesByIds
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - suix_getStakesByIds
      description: |
        Return one or more [DelegatedStake]. If a Stake was withdrawn its status will be Unstaked.
      summary: suix_getStakesByIds
      operationId: sui-suix_getStakesByIds
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: suix_getStakesByIds
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  items:
                    oneOf:
                      - title: staked_sui_ids
                        type: array
                        items:
                          $ref: "../components/schemas/ObjectID.yaml"
                        description: Array of staked SUI IDs
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "suix_getStakesByIds",
                  "params":
                    [
                      [
                        "0x378423de90ed03b694cecf443c72b5387b29a731d26d98108d7abc4902107d7d",
                        "0x6a8e0f8fea6fda5488462e58724c034462b6064a08845e2ae2942fe7c4ee816d",
                      ],
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    type: array
                    items:
                      $ref: "../components/schemas/DelegatedStake.yaml"
              example:
                $ref: "../components/examples/suix_getStakesByIds.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
