openapi: 3.1.0
info:
  title: unsafe_batchTransaction
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - unsafe_batchTransaction
      description: |
        Create an unsigned batched transaction.
      summary: unsafe_batchTransaction
      operationId: sui-unsafe_batchTransaction
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: "2.0"
                method:
                  type: string
                  default: unsafe_batchTransaction
                params:
                  type: array
                  minItems: 3
                  maxItems: 5
                  items:
                    oneOf:
                      - title: signer
                        $ref: "../components/schemas/SuiAddress.yaml"
                        description: The transaction signer's Sui address
                      - title: single_transaction_params
                        type: array
                        items:
                          $ref: "../components/schemas/RPCTransactionRequestParams.yaml"
                        description: List of transaction request parameters
                      - title: gas
                        $ref: "../components/schemas/ObjectID.yaml"
                        description: Gas object to be used in this transaction, node will pick one from the signer's possession if not provided
                      - title: gas_budget
                        $ref: "../components/schemas/BigInt_for_uint64.yaml"
                        description: The gas budget, the transaction will fail if the gas cost exceed the budget
                      - title: txn_builder_mode
                        $ref: "../components/schemas/SuiTransactionBlockBuilderMode.yaml"
                        description: Whether this is a regular transaction or a Dev Inspect Transaction
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    $ref: "../components/schemas/TransactionBlockBytes.yaml"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
