openapi: 3.1.0
info:
  title: solana-getBlockHeight
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getBlockHeight
      description: |
        Returns the current block height of the node.
      summary: getBlockHeight
      operationId: solana-getBlockHeight
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getBlockHeight
                params:
                  type: array
                  minItems: 0
                  maxItems: 1
                  description: |
                    It contains following items:
                    1. ConfigurationObject (`optional`)
                  items:
                    title: Configuration Object
                    type: object
                    properties:
                      commitment:
                        $ref: "../components/schemas/Commitment.yaml"
                      minContextSlot:
                        $ref: "../components/schemas/MinContextSlot.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getBlockHeight",
                  "params":
                    [
                      {
                        "commitment": "finalized",
                        "minContextSlot": "342288570",
                      },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: integer
                        description: Current block height.
              example:
                $ref: "../components/examples/getBlockHeight.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
