openapi: 3.1.0
info:
  title: solana-getBlockCommitment
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getBlockCommitment
      description: |
        Returns commitment for particular block.
      summary: getBlockCommitment
      operationId: solana-getBlockCommitment
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getBlockCommitment
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  description: |
                    It contains following items:
                    1. Block number (`required`)
                  items:
                    title: Block number
                    $ref: "../components/schemas/BlockNumber.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getBlockCommitment",
                  "params": [5],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          commitment:
                            type: array
                            description: Array of u64 integers logging the amount of cluster stake in lamports that has voted on the block at each depth from 0 to `MAX_LOCKOUT_HISTORY`.
                            items:
                              type: integer
                          totalStake:
                            type: integer
                            description: Total active stake, in lamports, of the current epoch.
              example:
                $ref: "../components/examples/getBlockCommitment.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
