openapi: 3.1.0
info:
  title: solana-getBlockProduction
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getBlockProduction
      description: |
        Returns recent block production information from the current or previous epoch.
      summary: getBlockProduction
      operationId: solana-getBlockProduction
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getBlockProduction
                params:
                  type: array
                  minItems: 0
                  maxItems: 1
                  description: |
                    It contains following items:
                    1. ConfigurationObject (`optional`)
                  items:
                    title: Configuration Object
                    type: object
                    properties:
                      commitment:
                        $ref: "../components/schemas/Commitment.yaml"
                      identity:
                        $ref: "../components/schemas/Identity.yaml"
                      range:
                        $ref: "../components/schemas/Range.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getBlockProduction",
                  "params":
                    [
                      {
                        "commitment": "finalized",
                        "identity": "12i8gndWWWMTRzJBFhnYkobNgZB3XMUUJq75HeUrshrk",
                        "range":
                          { "firstSlot": 363067597, "lastSlot": 364115359 },
                      },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          context:
                            type: object
                            description: An object containing metadata about the current state of the Solana network at the time of the request.
                            properties:
                              apiVersion:
                                type: string
                                description: The API version used for the request
                              slot:
                                type: integer
                                description: The slot number at which the request was evaluated
                          value:
                            type: integer
                            description: The lamport balance of the account
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
