openapi: 3.1.0
info:
  title: solana-getBlocks
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getBlocks
      description: |
        Returns a list of confirmed blocks between two slots.
      summary: getBlocks
      operationId: solana-getBlocks
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getBlocks
                params:
                  type: array
                  minItems: 1
                  maxItems: 3
                  description: |
                    It contains following items:
                    1. Start slot (`required`)
                    2. End slot (`optional`)
                    3. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Start slot
                        $ref: "../components/schemas/SlotNumber.yaml"
                      - title: End slot
                        $ref: "../components/schemas/SlotNumber.yaml"
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getBlocks",
                  "params":
                    [338967300, 338967310, { "commitment": "finalized" }],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: array
                        description: An array of u64 integers listing confirmed blocks between `start_slot` and either `end_slot` - if provided, or latest confirmed slot, inclusive. Max range allowed is 500,000 slots.
                        items:
                          type: integer
                          format: uint64
                example:
                  $ref: "../components/examples/getBlock.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
