openapi: 3.1.0
info:
  title: solana-getEpochSchedule
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getEpochSchedule
      description: |
        Returns the epoch schedule information from this cluster
      summary: getEpochSchedule
      operationId: solana-getEpochSchedule
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getEpochSchedule
              example:
                { "jsonrpc": "2.0", "id": 1, "method": "getEpochSchedule" }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          firstNormalEpoch:
                            type: integer
                            format: uint64
                            description: First normal-length epoch, log2(slotsPerEpoch) - log2(MINIMUM_SLOTS_PER_EPOCH)
                          firstNormalSlot:
                            type: integer
                            format: uint64
                            description: Minimum number of slots in an epoch, MINIMUM_SLOTS_PER_EPOCH * (2.pow(firstNormalEpoch) - 1)
                          leaderScheduleSlotOffset:
                            type: integer
                            format: uint64
                            description: The number of slots before beginning of an epoch to calculate a leader schedule for that epoch.
                          slotsPerEpoch:
                            type: integer
                            format: uint64
                            description: The maximum number of slots in each epoch.
                          warmup:
                            type: boolean
                            description: Whether epochs start short and grow.
                example:
                  $ref: "../components/examples/getEpochSchedule.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
