openapi: 3.1.0
info:
  title: solana-getEpochInfo
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getEpochInfo
      description: |
        Returns information about the current epoch
      summary: getEpochInfo
      operationId: solana-getEpochInfo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getEpochInfo
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  description: |
                    It contains following items:
                    1. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
                          minContextSlot:
                            $ref: "../components/schemas/MinContextSlot.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getEpochInfo",
                  "params": [{ "commitment": "finalized" }],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          absoluteSlot:
                            type: integer
                            format: uint64
                            description: The current slot
                          blockHeight:
                            type: integer
                            format: uint64
                            description: The current block height
                          epoch:
                            type: integer
                            format: uint64
                            description: The current epoch
                          slotIndex:
                            type: integer
                            format: uint64
                            description: The current slot relative to the start of the current epoch
                          slotsInEpoch:
                            type: integer
                            format: uint64
                            description: The number of slots in this epoch
                          transactionCount:
                            type: integer
                            format: uint64
                            description: Total number of transactions processed without error since genesis
                example:
                  $ref: "../components/examples/getEpochInfo.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
