openapi: 3.1.0
info:
  title: solana-getHealth
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getHealth
      description: |
        Returns the slot of the lowest confirmed block that has not been purged from the ledger
      summary: getHealth
      operationId: solana-getHealth
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getHealth
              example: { "jsonrpc": "2.0", "id": 1, "method": "getHealth" }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        oneOf:
                          - title: Healthy
                            type: string
                            description: |
                              If the node is healthy: "ok"
                          - title: Unhealthy
                            description: If the node is unhealthy, a JSON RPC error response is returned. The specifics of the error response are UNSTABLE and may change in the future
                            allOf:
                              - $ref: "../components/schemas/ErrorObject.yaml"
                              - type: object
                                properties:
                                  data:
                                    type: object
                                    properties:
                                      numSlotsBehind:
                                        type: integer
                                        description: The number of slots behind the current slot
                example:
                  $ref: "../components/examples/getHealth.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
