openapi: 3.1.0
info:
  title: solana-getInflationReward
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getInflationReward
      description: |
        Returns the specific inflation values for the current epoch
      summary: getInflationReward
      operationId: solana-getInflationReward
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getInflationReward
                params:
                  type: array
                  minItems: 0
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Addresses (`optional`)
                    2. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Addresses
                        type: array
                        description: An array of addresses to query, as base-58 encoded strings
                        items:
                          type: string
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
                          epoch:
                            type: string
                            description: The blockhash of query, as base-58 encoded string
                          minContextSlot:
                            $ref: "../components/schemas/MinContextSlot.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getInflationReward",
                  "params":
                    [
                      [
                        "6dmNQ5jwLeLk5REvio1JcMshcbvkYMwy26sJ8pbkvStu",
                        "BGsqMegLpV6n6Ve146sSX2dTjUMj3M92HnU8BbNRMhF2",
                      ],
                      { "epoch": 800, "commitment": "finalized" },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          epoch:
                            type: integer
                            description: Epoch for which reward occurred
                            format: uint64
                          effectiveSlot:
                            type: integer
                            description: The slot in which the rewards are effective
                            format: uint64
                          amount:
                            type: integer
                            description: Reward amount in lamports
                            format: uint64
                          postBalance:
                            type: integer
                            description: Post balance of the account in lamports
                            format: uint64
                          commission:
                            type: integer
                            description: Vote account commission when the reward was credited
                            format: uint8
                example:
                  $ref: "../components/examples/getInflationReward.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
