openapi: 3.1.0
info:
  title: solana-getLeaderSchedule
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getLeaderSchedule
      description: |
        Returns the leader schedule for an epoch
      summary: getLeaderSchedule
      operationId: solana-getLeaderSchedule
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getLeaderSchedule
                params:
                  type: array
                  minItems: 0
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Epoch (`optional`)
                    2. ConfigurationObject (`optional`)
                  items:
                    title: Configuration Object
                    type: object
                    properties:
                      commitment:
                        $ref: "../components/schemas/Commitment.yaml"
                      identity:
                        $ref: "../components/schemas/Identity.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getLeaderSchedule",
                  "params":
                    [
                      null,
                      {
                        "commitment": "processed",
                        "identity": "dv2eQHeP4RFrJZ6UeiZWoc3XTtmtZCUKxxCApCDcRNV",
                      },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        description: |
                          Returns null if requested epoch is not found, otherwise returns an object where:
                          - Keys are validator identities (as base-58 encoded strings)
                          - Values are arrays of leader slot indices relative to the first slot in the requested epoch
                example:
                  $ref: "../components/examples/getLeaderSchedule.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
