openapi: 3.1.0
info:
  title: solana-getMultipleAccounts
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getMultipleAccounts
      description: |
        Returns the account information for a list of Pubkeys.
      summary: getMultipleAccounts
      operationId: solana-getMultipleAccounts
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getMultipleAccounts
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Pubkeys (`required`)
                    2. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Pubkeys
                        type: array
                        description: An array of Pubkeys to query, as base-58 encoded strings (up to a maximum of 100)
                        items:
                          type: string
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
                          minContextSlot:
                            $ref: "../components/schemas/MinContextSlot.yaml"
                          dataSlice:
                            $ref: "../components/schemas/DataSlice.yaml"
                          encoding:
                            $ref: "../components/schemas/Encoding.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getMultipleAccounts",
                  "params":
                    [
                      [
                        "vines1vzrYbzLMRdu58ou5XTby4qAqVRLmqo36NKPTg",
                        "4fYNw3dojWmQ4dXtSGE9epjRGy9pFSx62YypT7avPYvA",
                      ],
                      { "encoding": "base58", "commitment": "finalized" },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          context:
                            $ref: "../components/schemas/Context.yaml"
                          value:
                            type: array
                            items:
                              $ref: "../components/schemas/Account.yaml"
                example:
                  $ref: "../components/examples/getMultipleAccounts.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
