openapi: 3.1.0
info:
  title: solana-getMaxRetransmitSlot
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getMaxRetransmitSlot
      description: |
        Get the max slot seen from retransmit stage.
      summary: getMaxRetransmitSlot
      operationId: solana-getMaxRetransmitSlot
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getMaxRetransmitSlot
              example:
                { "jsonrpc": "2.0", "id": 1, "method": "getMaxRetransmitSlot" }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: integer
                        format: uint64
                        description: The max slot seen from retransmit stage
                example:
                  $ref: "../components/examples/getMaxRetransmitSlot.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
