openapi: 3.1.0
info:
  title: solana-getMinimumBalanceForRentExemption
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getMinimumBalanceForRentExemption
      description: |
        Returns minimum balance required to make account rent exempt.
      summary: getMinimumBalanceForRentExemption
      operationId: solana-getMinimumBalanceForRentExemption
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getMinimumBalanceForRentExemption
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Account's Data Length (`required`)
                    2. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Account's Data Length
                        type: integer
                        description: The length of the account's data
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getMinimumBalanceForRentExemption",
                  "params": [50, { "commitment": "processed" }],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: integer
                        format: uint64
                        description: Minimum lamports required in the Account to remain rent free
                example:
                  $ref: "../components/examples/getMinimumBalanceForRentExemption.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
