openapi: 3.1.0
info:
  title: solana-getProgramAccounts
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getProgramAccounts
      description: |
        Returns all accounts owned by the provided program Pubkey
      summary: getProgramAccounts
      operationId: solana-getProgramAccounts
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getProgramAccounts
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Pubkey of program (`required`)
                    2. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Pubkey of program
                        type: string
                        description: Base-58 encoded Pubkey of the program to query
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
                          minContextSlot:
                            $ref: "../components/schemas/MinContextSlot.yaml"
                          withContext:
                            type: boolean
                            description: Wrap the result in an RpcResponse JSON object
                          encoding:
                            $ref: "../components/schemas/Encoding.yaml"
                          dataSlice:
                            $ref: "../components/schemas/DataSlice.yaml"
                          filters:
                            type: array
                            description: |
                              Filter results using up to 4 filter objects.
                            items:
                              type: object
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getProgramAccounts",
                  "params":
                    [
                      "4Nd1mBQtrMJVYVfKf2PJy9NZUZdTAsp7D4xWLs4gDB4T",
                      {
                        "commitment": "finalized",
                        "filters":
                          [
                            { "dataSize": 17 },
                            { "memcmp": { "offset": 4, "bytes": "3Mc6vR" } },
                          ],
                      },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: array
                        items:
                          type: object
                          properties:
                            pubkey:
                              type: string
                              description: The account Pubkey as base-58 encoded string
                            account:
                              $ref: "../components/schemas/Account.yaml"
                example:
                  $ref: "../components/examples/getProgramAccounts.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
