openapi: 3.1.0
info:
  title: solana-getRecentPrioritizationFees
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getRecentPrioritizationFees
      description: |
        Returns a list of prioritization fees from recent blocks.
      summary: getRecentPrioritizationFees
      operationId: solana-getRecentPrioritizationFees
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getRecentPrioritizationFees
                params:
                  type: array
                  minItems: 0
                  maxItems: 1
                  description: |
                    It contains following items:
                    1. Account addresses (`optional`)
                  items:
                    title: Account addresses
                    type: array
                    description: |
                      An array of Account addresses (up to a maximum of 128 addresses), as base-58 encoded strings. If this parameter is provided, the response will reflect a fee to land a transaction locking all of the provided accounts as writable.
                    items:
                      type: string
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getRecentPrioritizationFees",
                  "params": [["CxELquR1gPP8wHe33gZ4QxqGB3sZ9RSwsJ2KshVewkFY"]],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: array
                        items:
                          type: object
                          properties:
                            slot:
                              type: integer
                              format: uint64
                              description: Slot in which the fee was observed
                            prioritizationFee:
                              type: integer
                              format: uint64
                              description: The per-compute-unit fee paid by at least one successfully landed transaction, specified in increments of micro-lamports (0.000001 lamports)
                example:
                  $ref: "../components/examples/getRecentPrioritizationFees.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
