openapi: 3.1.0
info:
  title: solana-getSignaturesForAddress
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getSignaturesForAddress
      description: |
        Returns signatures for confirmed transactions that include the given address in their accountKeys list. Returns signatures backwards in time from the provided signature or most recent confirmed block
      summary: getSignaturesForAddress
      operationId: solana-getSignaturesForAddress
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getSignaturesForAddress
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Account address (`required`)
                    2. ConfigurationObject (`optional`)
                  items:
                    type: string
                  oneOf:
                    - title: Account address
                      type: string
                      description: Account address as base-58 encoded string
                    - title: Configuration Object
                      type: object
                      properties:
                        commitment:
                          $ref: "../components/schemas/Commitment.yaml"
                        minContextSlot:
                          $ref: "../components/schemas/MinContextSlot.yaml"
                        limit:
                          type: integer
                          description: Maximum transaction signatures to return (between 1 and 1,000).
                          default: 1000
                        before:
                          type: string
                          description: Start searching backwards from this transaction signature. If not provided the search starts from the top of the highest max confirmed block.
                        until:
                          type: string
                          description: Search until this transaction signature, if found before limit reached
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getSignaturesForAddress",
                  "params":
                    [
                      "Vote111111111111111111111111111111111111111",
                      { "commitment": "finalized", "limit": 1 },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: array
                        items:
                          type: object
                          properties:
                            signature:
                              type: string
                              description: Transaction signature as base-58 encoded string
                            slot:
                              type: integer
                              format: uint64
                              description: The slot that contains the block with the transaction
                            err:
                              $ref: "../components/schemas/Err.yaml"
                            memo:
                              type: string
                              description: Memo associated with the transaction, null if no memo is present
                            blockTime:
                              type: integer
                              format: int64
                              description: Estimated production time, as Unix timestamp (seconds since the Unix epoch) of when transaction was processed. null if not available.
                            confirmationStatus:
                              $ref: "../components/schemas/ConfirmationStatus.yaml"
                example:
                  $ref: "../components/examples/getSignaturesForAddress.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
