openapi: 3.1.0
info:
  title: solana-getSignatureStatuses
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getSignatureStatuses
      description: |
        Returns the statuses of a list of signatures. Each signature must be a txid, the first signature of a transaction.
        Unless the `searchTransactionHistory` configuration parameter is included, this method only searches the recent status cache of signatures, which retains statuses for all active slots plus `MAX_RECENT_BLOCKHASHES` rooted slots.
      summary: getSignatureStatuses
      operationId: solana-getSignatureStatuses
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getSignatureStatuses
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Transaction signatures (`required`)
                    2. ConfigurationObject (`optional`)
                  items:
                    type: string
                  oneOf:
                    - title: Transaction signatures
                      type: string
                      description: An array of transaction signatures to confirm, as base-58 encoded strings (up to a maximum of 256)
                    - title: Configuration Object
                      type: object
                      properties:
                        searchTransactionHistory:
                          type: boolean
                          description: |
                            if true - a Solana node will search its ledger cache for any signatures not found in the recent status cache
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getSignatureStatuses",
                  "params":
                    [
                      [
                        "5VERv8NMvzbJMEkV8xnrLkEaWRtSz9CosKDYjCJjBRnbJLgp8uirBgmQpjKhoR4tjF3ZpRzrFmBV6UjKdiSZkQUW",
                      ],
                      { "searchTransactionHistory": true },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          context:
                            $ref: "../components/schemas/Context.yaml"
                          value:
                            type: array
                            items:
                              type: object
                              properties:
                                slot:
                                  type: integer
                                  format: uint64
                                  description: The slot the transaction was processed
                                confirmations:
                                  type: integer
                                  format: uint64
                                  description: Number of blocks since signature confirmation, null if rooted, as well as finalized by a supermajority of the cluster
                                err:
                                  $ref: "../components/schemas/Err.yaml"
                                status:
                                  type: object
                                  description: |
                                    `DEPRECATED` Transaction status

                                    "Ok": <null> - Transaction was successful
                                    "Err": <ERR> - Transaction failed with TransactionError
                                confirmationStatus:
                                  $ref: "../components/schemas/ConfirmationStatus.yaml"
                example:
                  $ref: "../components/examples/getSignatureStatuses.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
