openapi: 3.1.0
info:
  title: solana-getSupply
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getSupply
      description: |
        Returns information about the current supply.
      summary: getSupply
      operationId: solana-getSupply
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getSupply
                params:
                  type: array
                  minItems: 0
                  maxItems: 1
                  description: |
                    It contains following items:
                    1. ConfigurationObject (`optional`)
                  items:
                    title: Configuration Object
                    type: object
                    properties:
                      commitment:
                        $ref: "../components/schemas/Commitment.yaml"
                      excludeNonCirculatingAccountsList:
                        type: boolean
                        description: Exclude non circulating accounts list from response
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getSupply",
                  "params":
                    [
                      {
                        "commitment": "finalized",
                        "excludeNonCirculatingAccountsList": true,
                      },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          context:
                            $ref: "../components/schemas/Context.yaml"
                          value:
                            type: object
                            properties:
                              total:
                                type: integer
                                format: uint64
                                description: Total supply in lamports
                              circulating:
                                type: integer
                                format: uint64
                                description: Circulating supply in lamports
                              nonCirculating:
                                type: integer
                                format: uint64
                                description: Non-circulating supply in lamports
                              nonCirculatingAccounts:
                                type: array
                                items:
                                  type: string
                                  description: An array of account addresses of non-circulating accounts, as strings. If excludeNonCirculatingAccountsList is enabled, the returned array will be empty.
                example:
                  $ref: "../components/examples/getSupply.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
