openapi: 3.1.0
info:
  title: solana-getTokenAccountBalance
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getTokenAccountBalance
      description: |
        Returns the token balance of an SPL Token account.
      summary: getTokenAccountBalance
      operationId: solana-getTokenAccountBalance
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getTokenAccountBalance
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Pubkey of Token Account (`required`)
                    2. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Pubkey of Token Account
                        type: string
                        description: Pubkey of Token account to query, as base-58 encoded string
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getTokenAccountBalance",
                  "params":
                    [
                      "7fUAJdStEuGbc3sM84cKRL6yYaaSstyLSU4ve5oovLS7",
                      { "commitment": "finalized" },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          context:
                            $ref: "../components/schemas/Context.yaml"
                          value:
                            type: object
                            properties:
                              amount:
                                type: string
                                description: The raw balance without decimals, a string representation of u64
                              decimals:
                                type: number
                                description: Number of base 10 digits to the right of the decimal place
                              uiAmount:
                                type: number
                                description: |
                                  `DEPRECATED` The balance, using mint-prescribed decimals
                              uiAmountString:
                                type: string
                                description: The balance as a string, using mint-prescribed decimals
                example:
                  $ref: "../components/examples/getTokenAccountBalance.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
