openapi: 3.1.0
info:
  title: solana-getTransaction
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getTransaction
      description: |
        Returns transaction details for a confirmed transaction
      summary: getTransaction
      operationId: solana-getTransaction
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getTransaction
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    It contains following items:
                    1. Transaction signature (`required`)
                    2. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Transaction signature
                        type: string
                        description: Transaction signature, as base-58 encoded string
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
                          maxSupportedTransactionVersion:
                            $ref: "../components/schemas/MaxSupportedTransactionVersion.yaml"
                          transactionDetails:
                            $ref: "../components/schemas/TransactionDetails.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getTransaction",
                  "params":
                    [
                      "5Pj5fCupXLUePYn18JkY8SrRaWFiUctuDTRwvUy2ML9yvkENLb1QMYbcBGcBXRrSVDjp7RjUwk9a3rLC6gpvtYpZ",
                      {
                        "commitment": "confirmed",
                        "maxSupportedTransactionVersion": 0,
                        "encoding": "json",
                      },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          blockTime:
                            type: integer
                            description: Estimated production time, as Unix timestamp (seconds since the Unix epoch) of when the transaction was processed. null if not available
                          meta:
                            $ref: "../components/schemas/TransactionMeta.yaml"
                          slot:
                            type: integer
                            description: The slot this transaction was processed in
                          transaction:
                            $ref: "../components/schemas/Transaction.yaml"
                          version:
                            $ref: "../components/schemas/TransactionVersion.yaml"
                example:
                  $ref: "../components/examples/getTransaction.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
