openapi: 3.1.0
info:
  title: solana-getTokenAccountsByOwner
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-getTokenAccountsByOwner
      description: |
        Returns all SPL Token accounts by token owner.
      summary: getTokenAccountsByOwner
      operationId: solana-getTokenAccountsByOwner
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: getTokenAccountsByOwner
                params:
                  type: array
                  minItems: 2
                  maxItems: 3
                  description: |
                    It contains following items:
                    1. Pubkey of Token Account (`required`)
                    2. Program (`required`)
                    3. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Pubkey of Token Account
                        type: string
                        description: Pubkey of account owner to query, as base-58 encoded string
                      - title: Program
                        type: object
                        properties:
                          mint:
                            type: string
                            description: Pubkey of the specific token Mint to limit accounts to, as base-58 encoded string
                          programId:
                            type: string
                            description: Pubkey of the Token program that owns the accounts, as base-58 encoded string
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
                          minContextSlot:
                            $ref: "../components/schemas/MinContextSlot.yaml"
                          dataSlice:
                            $ref: "../components/schemas/DataSlice.yaml"
                          encoding:
                            $ref: "../components/schemas/Encoding.yaml"
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "getTokenAccountsByOwner",
                  "params":
                    [
                      "A1TMhSGzQxMr1TboBKtgixKz1sS6REASMxPo1qsyTSJd",
                      {
                        "programId": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
                      },
                      { "commitment": "finalized", "encoding": "jsonParsed" },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          context:
                            $ref: "../components/schemas/Context.yaml"
                          value:
                            type: object
                            properties:
                              pubkey:
                                type: string
                                description: The account Pubkey as base-58 encoded string
                              account:
                                $ref: "../components/schemas/Account.yaml"
                example:
                  $ref: "../components/examples/getTokenAccountsByOwner.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
