openapi: 3.1.0
info:
  title: solana-simulateTransaction
  version: 1.2.17
servers:
  - url: https://{solana-network}.nodit.io
    variables:
      solana-network:
        $ref: ../components/schemas/Network.yaml
components:
  securitySchemes:
    api_key:
      $ref: ../components/securitySchemes/X-API-KEY.yaml
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - solana-http-method-simulateTransaction
      description: Simulate sending a transaction
      summary: simulateTransaction
      operationId: solana-simulateTransaction
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jsonrpc
                - id
                - method
                - params
              properties:
                jsonrpc:
                  type: string
                  default: "2.0"
                id:
                  type: integer
                  default: 1
                method:
                  type: string
                  default: simulateTransaction
                params:
                  type: array
                  minItems: 1
                  maxItems: 2
                  description: |
                    It contains following items:
                      1. Transaction (`required`)
                      2. ConfigurationObject (`optional`)
                  items:
                    oneOf:
                      - title: Transaction
                        type: string
                        description: Transaction, as an encoded string.
                      - title: Configuration Object
                        type: object
                        properties:
                          commitment:
                            $ref: "../components/schemas/Commitment.yaml"
                            default: finalized
                          encoding:
                            $ref: "../components/schemas/EncodingForTransaction.yaml"
                          replaceRecentBlockhash:
                            type: boolean
                            description: |
                              If true the transaction recent blockhash will be replaced with the most recent blockhash (conflicts with `sigVerify`)
                          sigVerify:
                            type: boolean
                            description: |
                              If true the transaction signatures will be verified (conflicts with replaceRecentBlockhash)
                          minContextSlot:
                            $ref: "../components/schemas/MinContextSlot.yaml"
                          innerInstructions:
                            type: boolean
                            description: |
                              If true the response will include inner instructions. These inner instructions will be jsonParsed where possible, otherwise json.
                          accounts:
                            type: array
                            items:
                              type: object
                              properties:
                                addresses:
                                  type: string
                                  description: An array of accounts to return, as base-58 encoded strings
                                encoding:
                                  type: string
                                  description: |
                                    Encoding for returned Account data. Note: jsonParsed encoding attempts to use program-specific state parsers to return more human-readable and explicit account state data. If jsonParsed is requested but a parser cannot be found, the field falls back to base64 encoding, detectable when the returned accounts.data field is type string.
              example:
                {
                  "jsonrpc": "2.0",
                  "id": 1,
                  "method": "simulateTransaction",
                  "params":
                    [
                      "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEEjNmKiZGiOtSZ+g0//wH5kEQo3+UzictY+KlLV8hjXcs44M/Xnr+1SlZsqS6cFMQc46yj9PIsxqkycxJmXT+veJjIvefX4nhY9rY+B5qreeqTHu4mG6Xtxr5udn4MN8PnBt324e51j94YQl285GzN2rYa/E2DuQ0n/r35KNihi/zamQ6EeyeeVDvPVgUO2W3Lgt9hT+CfyqHvIa11egFPCgEDAwIBAAkDZAAAAAAAAAA=",
                      {
                        "commitment": "confirmed",
                        "encoding": "base64",
                        "replaceRecentBlockhash": true,
                      },
                    ],
                }
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../components/schemas/SuccessfulResponse.yaml"
                  - type: object
                    properties:
                      result:
                        type: object
                        properties:
                          context:
                            $ref: "../components/schemas/Context.yaml"
                          value:
                            type: object
                            properties:
                              accounts:
                                type: array
                                items:
                                  $ref: "../components/schemas/Account.yaml"
                              err:
                                $ref: "../components/schemas/Err.yaml"
                              innerInstructions:
                                type: array
                                description: Defined only if innerInstructions was set to true. The value is a list of inner instructions.
                                items:
                                  $ref: "../components/schemas/InnerInstruction.yaml"
                              loadedAccountsDataSize:
                                type: integer
                                description: The number of bytes of all accounts loaded by this transaction
                              logs:
                                type: array
                                description: Array of log messages the transaction instructions output during execution, null if simulation failed before the transaction was able to execute
                                items:
                                  type: string
                              replacementBlockhash:
                                type: object
                                properties:
                                  blockhash:
                                    $ref: "../components/schemas/Blockhash.yaml"
                                  lastValidBlockHeight:
                                    type: integer
                                    format: uint64
                                    description: The last valid block height at which the blockhash is still valid.
                              returnData:
                                type: object
                                description: |
                                  The most-recent return data generated by an instruction in the transaction
                                properties:
                                  programId:
                                    type: string
                                    description: the program that generated the return data, as base-58 encoded Pubkey
                                  data:
                                    type: string
                                    description: the return data itself, as base-64 encoded binary data
                example:
                  $ref: "../components/examples/simulateTransaction.json"
        "400":
          $ref: "../components/responses/400.yaml"
        "401":
          $ref: "../components/responses/401.yaml"
        "403":
          $ref: "../components/responses/403.yaml"
        "404":
          $ref: "../components/responses/404.yaml"
        "429":
          $ref: "../components/responses/429.yaml"
