openapi: 3.1.0
info:
  title: Cosmos - Validators
  version: 1.0.0
servers:
  - url: https://rpc-cosmos-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      operationId: validators
      summary: Validators
      description: Retrieves the validator list at the specified block height.
      tags:
        - json-rpc-api
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - jsonrpc
                - id
                - method
              properties:
                jsonrpc:
                  type: string
                  const: "2.0"
                id:
                  type: integer
                method:
                  type: string
                  const: validators
                params:
                  type: object
                  additionalProperties: false
                  properties:
                    height:
                      type: string
                      description: Block height to query validators.
                    page:
                      type: string
                      description: Page number.
                    per_page:
                      type: string
                      description: Number of items per page.
            example:
              jsonrpc: "2.0"
              id: 1
              method: validators
              params:
                height: "1"
                page: "1"
                per_page: "20"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - jsonrpc
                  - id
                  - result
                properties:
                  jsonrpc:
                    type: string
                    const: "2.0"
                  id:
                    type: integer
                  result:
                    type: object
                    additionalProperties: false
                    properties:
                      block_height:
                        type: string
                      validators:
                        type: array
                        items:
                          type: object
                          additionalProperties: false
                          properties:
                            address:
                              type: string
                            pub_key:
                              type: object
                              additionalProperties: false
                              properties:
                                type:
                                  type: string
                                value:
                                  type: string
                            voting_power:
                              type: string
                            proposer_priority:
                              type: string
                      count:
                        type: string
                      total:
                        type: string
              example:
                jsonrpc: "2.0"
                id: 1
                result:
                  block_height: "1"
                  validators:
                    - address: B00A6323737F321EB0B8D59C6FD497A14B60938A
                      pub_key:
                        type: tendermint/PubKeyEd25519
                        value: oX8HyvloaslMOq50t0UjM5WkxaB3VJFQ/E3AYkM/GKE=
                      voting_power: "1000000"
                      proposer_priority: "0"
                  count: "1"
                  total: "1"
