openapi: 3.1.0
info:
  title: Babylon - cosmos_bank_v1beta1_params
  version: 1.0.0
servers:
  - url: https://rest-babylon-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /cosmos/bank/v1beta1/params:
    get:
      description: Params queries the parameters of x/bank module.
      operationId: cosmos_bank_v1beta1_params
      tags:
        - bank
      responses:
        "200":
          description: Successful Response
          content:
            "*/*":
              schema:
                type: object
                properties:
                  params:
                    description: params provides the parameters of the bank module.
                    type: object
                    properties:
                      send_enabled:
                        type: array
                        items:
                          type: object
                          properties:
                            denom:
                              type: string
                            enabled:
                              type: boolean
                          description: |-
                            SendEnabled maps coin denom to a send_enabled status (whether a denom is
                            sendable).
                        description: |-
                          Deprecated: Use of SendEnabled in params is deprecated.
                          For genesis, use the newly added send_enabled field in the genesis object.
                          Storage, lookup, and manipulation of this information is now in the keeper.

                          As of cosmos-sdk 0.47, this only exists for backwards compatibility of genesis files.
                      default_send_enabled:
                        type: boolean
                description: QueryParamsResponse defines the response type for querying x/bank parameters.
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      security:
        - api_key: []
      summary: /cosmos/bank/v1beta1/params
