openapi: 3.1.0
info:
  title: Babylon - cosmos_distribution_v1beta1_validators_{validator_address}_slashes
  version: 1.0.0
servers:
  - url: https://rest-babylon-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /cosmos/distribution/v1beta1/validators/{validator_address}/slashes:
    get:
      description: Retrieves the slash events of the validator.
      operationId: cosmos_distribution_v1beta1_validators_{validator_address}_slashes
      tags:
        - distribution
      responses:
        "200":
          description: Successful Response
          content:
            "*/*":
              schema:
                type: object
                properties:
                  slashes:
                    type: array
                    items:
                      type: object
                      properties:
                        validator_period:
                          type: string
                          format: uint64
                        fraction:
                          type: string
                      description: |-
                        ValidatorSlashEvent represents a validator slash event.
                        Height is implicit within the store key.
                        This is needed to calculate appropriate amount of staking tokens
                        for delegations which are withdrawn after a slash has occurred.
                    description: List of slashes received by the validator.
                  pagination:
                    description: pagination defines an pagination for the response.
                    type: object
                    properties:
                      next_key:
                        type: string
                        format: byte
                        description: |-
                          next_key is the key to be passed to PageRequest.key to
                          query the next page most efficiently. It will be empty if
                          there are no more results.
                      total:
                        type: string
                        format: uint64
                        title: |-
                          total is total number of results available if PageRequest.count_total
                          was set, its value is undefined otherwise
                description: |-
                  QueryValidatorSlashesResponse is the response type for the
                  Query/ValidatorSlashes RPC method.
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      parameters:
        - name: validator_address
          description: Validator address to query.
          in: path
          required: true
          schema:
            type: string
        - name: starting_height
          description: starting_height defines the optional starting height to query the slashes.
          in: query
          required: false
          schema:
            type: string
            format: uint64
        - name: ending_height
          description: starting_height defines the optional ending height to query the slashes.
          in: query
          required: false
          schema:
            type: string
            format: uint64
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          schema:
            type: string
            format: byte
        - name: pagination.offset
          description: |-
            offset is a numeric offset that can be used when key is unavailable.
            It is less efficient than using key. Only one of offset or key should
            be set.
          in: query
          required: false
          schema:
            type: string
            format: uint64
        - name: pagination.limit
          description: |-
            limit is the total number of results to be returned in the result page.
            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          schema:
            type: string
            format: uint64
        - name: pagination.count_total
          description: |-
            count_total is set to true  to indicate that the result set should include
            a count of the total number of items available for pagination in UIs.
            count_total is only respected when offset is used. It is ignored when key
            is set.
          in: query
          required: false
          schema:
            type: boolean
        - name: pagination.reverse
          description: Set to true to return results in descending order.
          in: query
          required: false
          schema:
            type: boolean
      security:
        - api_key: []
      summary: /cosmos/distribution/v1beta1/validators/{validator_address}/slashes
