openapi: 3.1.0
info:
  title: SEI - cosmos_distribution_v1beta1_delegators_{delegator_address}_rewards_{validator_address}
  version: 1.0.0
servers:
  - url: https://rest-sei-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /cosmos/distribution/v1beta1/delegators/{delegator_address}/rewards/{validator_address}:
    get:
      description: DelegationRewards queries the total rewards accrued by a delegation.
      operationId: cosmos_distribution_v1beta1_delegators_{delegator_address}_rewards_{validator_address}
      tags:
        - distribution
      responses:
        "200":
          description: Successful Response
          content:
            "*/*":
              schema:
                type: object
                properties:
                  rewards:
                    type: array
                    items:
                      type: object
                      properties:
                        denom:
                          type: string
                        amount:
                          type: string
                      description: |-
                        DecCoin defines a token with a denomination and a decimal amount.

                        NOTE: The amount field is an Dec which implements the custom method
                        signatures required by gogoproto.
                    description: rewards defines the rewards accrued by a delegation.
                description: |-
                  QueryDelegationRewardsResponse is the response type for the
                  Query/DelegationRewards RPC method.
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      parameters:
        - name: delegator_address
          description: delegator_addr defines the delegator address to query for.
          in: path
          required: true
          schema:
            type: string
        - name: validator_address
          description: Validator address to query.
          in: path
          required: true
          schema:
            type: string
      security:
        - api_key: []
      summary: /cosmos/distribution/v1beta1/delegators/{delegator_address}/rewards/{validator_address}
