openapi: 3.1.0
info:
  title: Initia - initia_mstaking_v1_validators_{validator_address}
  version: 1.0.0
servers:
  - url: https://rest-initia-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /initia/mstaking/v1/validators/{validator_address}:
    get:
      description: Returns validator information for the given validator address.
      operationId: initia_mstaking_v1_validators_{validator_address}
      tags:
        - mstaking
      responses:
        "200":
          description: Successful Response
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
      parameters:
        - name: validator_address
          description: Validator operator address (bech32).
          in: path
          required: true
          example: initvaloper1hq2gma6r9s9yz5klk0ra5gtwhxf2f6va7eqwep
          schema:
            type: string
      security:
        - api_key: []
      summary: /initia/mstaking/v1/validators/{validator_address}
