openapi: 3.1.0
info:
  title: bnb
  version: 1.2.20
servers:
  - url: https://web3.nodit.io/v1
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: >-
        The default value, `nodit-demo`, is only for use in the developer
        documentation. For real applications or services, use the API key
        obtained from the Nodit console.
paths: {}
