openapi: 3.1.0
info:
  title: evm-kaia-klay_uninstallFilter
  version: 1.2.10
servers:
  - url: https://{kaia-network}.nodit.io
    variables:
      kaia-network:
        default: kaia-mainnet
        enum:
          - kaia-mainnet
          - kaia-kairos
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: >-
        The default value, `nodit-demo`, is only for use in the developer
        documentation. For real applications or services, use the API key
        obtained from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - evm-kaia-klay_uninstallFilter
      description: >-
        필터 ID를 입력하여 해당 필터를 제거합니다. 필터 ID는 klay_newFilter 메서드를 통해 생성된 필터 ID를
        입력합니다. 필터가 이미 제거되었거나 존재하지 않는 경우에는 `false`를 반환합니다.
      summary: klay_uninstallFilter
      operationId: kaia-klay_uninstallFilter
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: klay_uninstallFilter
                params:
                  type: array
                  items:
                    oneOf:
                      - title: Filter ID
                        type: string
                        pattern: ^0[xX][0-9a-fA-F]{32}
                        default: '0xaf35d60b70eb3b54018456a0d365ea49'
                        description: >-
                          필터 ID는 필터를 생성할 때 반환되는 고유 식별자입니다. 필터 ID는 16진수 문자열로
                          표현됩니다.
                  minItems: 1
                  maxItems: 1
                  default:
                    - '0xaf35d60b70eb3b54018456a0d365ea49'
                  description: |-
                    다음 파라미터들을 타입에 맞게 배열로 입력합니다.
                    1. `filter ID`: 미리 생성한 필터 ID를 입력합니다.
      responses:
        '200':
          description: Successful Response
          content:
            application/json: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error_code
                properties:
                  message:
                    type: string
                  error_code:
                    type: string
                    description: >-
                      These codes provide more granular error information beyond
                      just the HTTP status code of the response.


                      Allowed values: account_not_found, resource_not_found,
                      module_not_found, struct_field_not_found,
                      version_not_found, transaction_not_found,
                      table_item_not_found, block_not_found,
                      state_value_not_found, version_pruned, block_pruned,
                      invalid_input, invalid_transaction_update,
                      sequence_number_too_old, vm_error, health_check_failed,
                      mempool_is_full, internal_error, web_framework_error,
                      bcs_not_supported, api_disabled
                  vm_error_code:
                    type: integer
                    description: >-
                      A code providing VM error details when submitting
                      transactions to the VM.
