openapi: 3.1.0
info:
  title: evm-ethereum-trace_filter
  version: 1.2.16
servers:
  - url: https://{ethereum-network}.nodit.io
    variables:
      ethereum-network:
        default: ethereum-mainnet
        enum:
          - ethereum-mainnet
          - ethereum-sepolia
          - ethereum-hoodi
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: >-
        The default value, `nodit-demo`, is only for use in the developer
        documentation. For real applications or services, use the API key
        obtained from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - evm-ethereum-trace_filter
      description: >
        ì§€ì •ëœ ì¡°ê±´ì— ë§žëŠ” íŠ¸ëžœìž­ì…˜ë“¤ì˜ ì‹¤í–‰ ê³¼ì •ì„ í•„í„°ë§í•˜ì—¬ ì¶”ì í•©ë‹ˆë‹¤. ì‚¬ìš©ìžëŠ” ë¸”ë¡ ë²ˆí˜¸ì˜ ë²”ìœ„, ì‚¬ìš©ëœ ì£¼ì†Œ, ì‚¬ìš©ëœ í† í° ë“±
        ë‹¤ì–‘í•œ ì¡°ê±´ì„ ì„¤ì •í•  ìˆ˜ ìžˆìœ¼ë©°, ì´ì— í•´ë‹¹í•˜ëŠ” íŠ¸ëžœìž­ì…˜ë“¤ì˜ ì¶”ì  ì •ë³´ë¥¼ ì–»ì„ ìˆ˜ ìžˆìŠµë‹ˆë‹¤.



        > ðŸš§ ì‘ë‹µ ì‹œê°„ì´ ì˜¤ëž˜ ê±¸ë¦¬ì‹œë‚˜ìš”? ë¸”ë¡ ë²”ìœ„ì— ë”°ë¼ ì‘ë‹µ ì‹œê°„ì´ ê¸¸ì–´ì§ˆ ìˆ˜ ìžˆìŠµë‹ˆë‹¤!

        >

        > ë„“ì€ ë¸”ë¡ ë²”ìœ„ë¥¼ ì§€ì •í•˜ê±°ë‚˜ ì´ë²¤íŠ¸ê°€ ë§Žì€ ë¸”ë¡ì„ í¬í•¨í•˜ë©´, ì‘ë‹µì´ ì§€ì—°ë˜ê±°ë‚˜ íƒ€ìž„ì•„ì›ƒì´ ë°œìƒí•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤.

        >

        > ë¹ ë¥¸ ì‘ë‹µì„ ì›í•˜ì‹ ë‹¤ë©´ ë‹¤ìŒ ê¶Œìž¥ì‚¬í•­ì„ ì°¸ê³ í•˜ì„¸ìš”:

        >

        > - fromBlock ~ toBlock ë²”ìœ„ëŠ” 1000 ë¸”ë¡ ì´í•˜ë¡œ ì„¤ì •í•˜ëŠ” ê²ƒì´ ì¢‹ìŠµë‹ˆë‹¤.

        > - íŠ¹ížˆ blockTagì— latestë¥¼ ì‚¬ìš©í•˜ëŠ” ê²½ìš°, ë‚´ë¶€ì ìœ¼ë¡œ ëª…í™•í•œ ë¸”ë¡ ë²ˆí˜¸ë¥¼ ì•Œ ìˆ˜ ì—†ì–´ ì‘ë‹µ ì‹œê°„ì´ ê¸¸ì–´ì§ˆ ìˆ˜
        ìžˆìŠµë‹ˆë‹¤.
          ì´ ê²½ìš°, eth_blockNumberë¡œ ìµœì‹  ë¸”ë¡ ë²ˆí˜¸ë¥¼ ì¡°íšŒí•œ í›„ ëª…ì‹œì ìœ¼ë¡œ ì§€ì •í•˜ì„¸ìš”.
      summary: trace_filter
      operationId: trace_filter
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: trace_filter
                params:
                  type: array
                  items:
                    oneOf:
                      - title: Trace Object
                        type: object
                        properties:
                          fromBlock: &ref_0
                            title: Block Number
                            type: string
                            pattern: ^0[xX][0-9a-fA-F]+$
                            default: '0x1076B5A'
                            description: ë¸”ë¡ ë„˜ë²„ëŠ” ë¸”ë¡ì˜ ìˆœì„œë¥¼ ë‚˜íƒ€ë‚´ëŠ” ìˆ«ìžìž…ë‹ˆë‹¤. ë¸”ë¡ ë„˜ë²„ëŠ” 16ì§„ìˆ˜ ë¬¸ìžì—´ë¡œ í‘œí˜„ë©ë‹ˆë‹¤.
                          toBlock: *ref_0
                          fromAddress:
                            type: array
                            items: &ref_1
                              title: Address
                              type: string
                              pattern: ^0[xX][0-9a-fA-F]{40}$
                              default: '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045'
                              description: >-
                                ì£¼ì†ŒëŠ” 20ë°”ì´íŠ¸ ê¸¸ì´ì˜ 16ì§„ìˆ˜ ë¬¸ìžì—´ë¡œ í‘œí˜„ë˜ë©°, EVM ê³„ì—´ì˜ ë¸”ë¡ì²´ì¸ì—ì„œ
                                ì‚¬ìš©ë˜ëŠ” ì£¼ì†Œ í˜•ì‹ìž…ë‹ˆë‹¤.
                            description: í•„í„°ë§í•˜ê³ ìž í•˜ëŠ” from ì£¼ì†Œë¥¼ ë°°ì—´ í˜•ì‹ìœ¼ë¡œ ìž…ë ¥í•©ë‹ˆë‹¤.
                          toAddress:
                            type: array
                            items: *ref_1
                            description: í•„í„°ë§í•˜ê³ ìž í•˜ëŠ” to ì£¼ì†Œë¥¼ ë°°ì—´ í˜•ì‹ìœ¼ë¡œ ìž…ë ¥í•©ë‹ˆë‹¤.
                          after:
                            type: string
                            pattern: ^0[xX][0-9a-fA-F]+$
                            description: traceí•˜ê³ ìž í•˜ëŠ” offset í¬ê¸°ìž…ë‹ˆë‹¤.
                          count:
                            type: integer
                            description: trace batchì— í‘œê¸°í•˜ê³ ìž í•˜ëŠ” í•´ë‹¹ traceì˜ ìˆ˜ìž…ë‹ˆë‹¤.
                        description: Traceí•  í•„í„° ì˜µì…˜ì„ Object í˜•ì‹ìœ¼ë¡œ ìž…ë ¥í•©ë‹ˆë‹¤.
                  minItems: 1
                  maxItems: 1
                  default:
                    - fromBlock: '0x1253B3F'
                      toBlock: '0x1253B5F'
                      fromAddress:
                        - '0xB287eaC48aB21c5FB1d3723830d60b4c797555B0'
                  description: |-
                    ë‹¤ìŒ íŒŒë¼ë¯¸í„°ë“¤ì„ íƒ€ìž…ì— ë§žê²Œ ë°°ì—´ë¡œ ìž…ë ¥í•©ë‹ˆë‹¤.

                    1. `trace object`: Traceí•  í•„í„° ì˜µì…˜ì„ Object í˜•ì‹ìœ¼ë¡œ ìž…ë ¥í•©ë‹ˆë‹¤.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              example:
                jsonrpc: '2.0'
                id: 1
                result:
                  - action:
                      callType: call
                      from: '0xb287eac48ab21c5fb1d3723830d60b4c797555b0'
                      gas: '0x0'
                      input: 0x
                      to: '0x6a78a5f8a7839a234dee4de29c26c5f6ebad5caa'
                      value: '0x521153de4fc000'
                    blockHash: >-
                      0x7a1e8b72cbb07cae9c4b1d4fa32593ff2446c8a0a8e65ee9dadd6fb2f04862eb
                    blockNumber: 19217231
                    result:
                      gasUsed: '0x0'
                      output: 0x
                    subtraces: 0
                    traceAddress: []
                    transactionHash: >-
                      0x3b60b4393fbc01b2ec6a0a24c0c39b42ee49c0dded76f1eb5af623004d2ddc6e
                    transactionPosition: 62
                    type: call
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error_code
                properties:
                  message:
                    type: string
                  error_code:
                    type: string
                    description: >-
                      These codes provide more granular error information beyond
                      just the HTTP status code of the response.


                      Allowed values: account_not_found, resource_not_found,
                      module_not_found, struct_field_not_found,
                      version_not_found, transaction_not_found,
                      table_item_not_found, block_not_found,
                      state_value_not_found, version_pruned, block_pruned,
                      invalid_input, invalid_transaction_update,
                      sequence_number_too_old, vm_error, health_check_failed,
                      mempool_is_full, internal_error, web_framework_error,
                      bcs_not_supported, api_disabled
                  vm_error_code:
                    type: integer
                    description: >-
                      A code providing VM error details when submitting
                      transactions to the VM.
