openapi: 3.1.0
info:
  title: evm-polygon-debug_traceCall
  version: 1.2.10
servers:
  - url: https://{polygon-network}.nodit.io
    variables:
      polygon-network:
        default: polygon-mainnet
        enum:
          - polygon-mainnet
          - polygon-amoy
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: >-
        The default value, `nodit-demo`, is only for use in the developer
        documentation. For real applications or services, use the API key
        obtained from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - evm-polygon-debug_traceCall
      description: >-
        eth_call을 디버깅 모드로 실행하면서 trace 기능을 제공합니다. 현재 블록의 상태를 기반으로 특정 call을 수행하였을
        때 발생하는 모든 스택 변화를 추적할 수 있습니다.
      summary: debug_traceCall
      operationId: polygon-debug_traceCall
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: debug_traceCall
                params:
                  type: array
                  items:
                    oneOf:
                      - title: Call Object
                        type: object
                        properties:
                          from:
                            type: string
                            description: 트랜잭션의 from 주소를 문자열 형식으로 입력합니다.
                          to:
                            type: string
                            description: 트랜잭션의 to 주소를 문자열 형식으로 입력합니다.
                            default: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
                          gas:
                            type: string
                            description: >-
                              해당 트랜잭션을 처리하기 위해 필요한 가스의 소모량을 hex형식의 문자열로 입력합니다.
                              스마트 컨트랙트 call을 수행하는 경우 소모되는 가스가 없으므로 0x0로 입력할 수
                              있습니다.
                          gasPrice:
                            type: string
                            description: 설정하고자 하는 가스당 비용을 hex 형식의 문자열로 입력합니다.
                          value:
                            type: string
                            description: 트랜잭션의 value 값입니다.
                          data:
                            type: string
                            description: >-
                              실행하고자 하는 트랜잭션의 method signature 해시값입니다. ABI에서 참고할
                              수 있습니다.
                            default: >-
                              0x70a08231000000000000000000000000d8dA6BF26964aF9D7eEd9e03E53415D37aA96045
                        description: >-
                          트랜잭션을 시뮬레이션하기 위한 call object입니다. 다음 필드를 포함할 수 있습니다.

                          * `from`: 트랜잭션의 from 주소를 문자열 형식으로 입력합니다.

                          * `to` : 트랜잭션의 to 주소를 문자열 형식으로 입력합니다.

                          * `gas` : 해당 트랜잭션을 처리하기 위해 필요한 가스의 소모량을 hex형식의 문자열로
                          입력합니다. 스마트 컨트랙트 call을 수행하는 경우 소모되는 가스가 없으므로 0x0로 입력할 수
                          있습니다.

                          * `gasPrice` : 설정하고자 하는 가스당 비용을 hex 형식의 문자열로 입력합니다.

                          * `value` : 트랜잭션의 value 값입니다.

                          * `data` : 실행하고자 하는 트랜잭션의 method signature 해시값입니다.
                          ABI에서 참고할 수 있습니다.
                      - title: Block Identifier
                        type: string
                        oneOf:
                          - title: Block Number
                            type: string
                            pattern: ^0[xX][0-9a-fA-F]+$
                            default: '0x1076B5A'
                            description: 블록 넘버는 블록의 순서를 나타내는 숫자입니다. 블록 넘버는 16진수 문자열로 표현됩니다.
                          - title: Block Hash
                            type: string
                            pattern: ^0[xX][0-9a-fA-F]{64}
                            default: >-
                              0x39008d07edf93c03bb9d1cfc80598fcf63f441ec86e9de3733fa6a484980ca48
                            description: >-
                              블록 해시는 블록의 고유 식별자입니다. 블록 해시값은 64자리 16진수 문자열로
                              표현됩니다.
                          - title: Block Tag
                            type: string
                            pattern: ^(latest|earliest|pending|safe|finalized)$
                            default: latest
                            description: >-
                              블록 태그는 다음 중 하나를 사용하여 블록을 지정할 수 있습니다.

                              * `earliest`: 체인에서 사용 가능한 가장 오래된 블록을 나타냅니다.

                              * `finalized`: 최근에 확정된 블록을 나타내며, 이는 더 이상 변경될 수 없는
                              안정적인 상태의 블록을 의미합니다. 이 용어는 주로 지분 증명(PoS) 블록체인에서
                              사용되며, 블록이 최종적으로 확정되었음을 나타냅니다.

                              * `safe`: 네트워크에 의해 안전하게 간주되는 최근 블록을 나타냅니다. '안전'한
                              블록은 네트워크 재조직(reorgs)의 위험 없이 신뢰할 수 있는 것으로 간주됩니다.

                              * `latest`: 현재 체인의 가장 최근 블록을 나타내며, 아직 최종 확정되지 않았을
                              수 있어 재조직(reorgs)될 가능성이 있습니다. 이는 일반적으로 가장 최신의 상태를
                              조회할 때 사용됩니다.

                              * `pending`: 아직 채굴되지 않은, 메모리 풀에 있는 트랜잭션들을 포함할 예정인
                              다음 블록을 나타냅니다. 이는 주로 예정된 트랜잭션들의 상태를 확인할 때 사용됩니다.
                        default: '0x12C1A00'
                        description: >-
                          블록 지정을 위해 블록 해시, 블록 넘버, 또는 블록 태그 중 하나를 사용할 수 있습니다.

                          * 블록 넘버: 16진수 문자열 (ex. "0x1") 

                          * 블록 해시: 64자리 16진수 문자열 (ex.
                          "0x39008d07edf93c03bb9d1cfc80598fcf63f441ec86e9de3733fa6a484980ca48")]

                          * 블록 태그: enum 문자열 (ex. "latest", "earliest",
                          "pending")
                      - title: Trace Option Object
                        type: object
                        properties:
                          tracer:
                            type: string
                            enum:
                              - callTracer
                              - prestateTracer
                            default: callTracer
                            description: >-
                              tracer의 타입을 지정하는 필드로, "callTracer" 또는
                              "prestateTracer" 값 중 하나로 지정합니다.

                              1. `callTracer` : callTracer는 실행된 트랜잭션의 실행 경로와 결과를
                              확인하는 데 사용됩니다. 트랜잭션의 호출 스택, 반환 값, 가스 소비량, Revert 사유
                              등의 정보를 제공하며, 스마트 계약의 함수 호출과 상호작용하는 과정을 추적할 수 있습니다.
                              실행 옵션(onlyTopCall)에 따라 특정 call의 nested call들을 모두
                              조회하여 추적할 수 있습니다.

                              2. `prestateTracer`: prestateTracer는 특정 트랜잭션이나 블록이
                              실행되기 전의 상태(pre-state)를 추적하는 도구입니다. 트랜잭션이 실행되기 전의
                              계정 상태와 계약 코드를 기록하며, 트랜잭션의 실행 전과 후의 상태 변화를 분석할 수
                              있습니다. prestateTracer는 스마트 계약의 상태 변경 및 계정 간 상호작용을
                              추적하는 데 사용됩니다.
                          tracerConfig:
                            type: object
                            properties:
                              onlyTopCall:
                                type: boolean
                                default: true
                            description: >-
                              tracer 설정을 위한 Object입니다. Boolean 타입의 "onlyTopCall"
                              옵션을 사용할 수 있으며, true로 설정하는 경우 main call에 대한 이력만
                              trace합니다. false로 설정하는 경우 sub-call 레벨까지 trace합니다.
                        description: 'trace 옵션 설정을 위한 object입니다. '
                  minItems: 3
                  maxItems: 3
                  default:
                    - from: '0xc90d3Ac75D1D36dF0b0a229E73D8409FB7F3c4ab'
                      to: '0xd3CdA913deB6f67967B99D67aCDFa1712C293601'
                      value: '0x186a0'
                    - finalized
                    - tracer: callTracer
                  description: >-
                    다음 파라미터들을 타입에 맞게 배열로 입력합니다.


                    1. `call object` - 호출할 컨트랙트의 주소와 호출할 함수의 데이터를 입력합니다.

                    2. `block identifier` - 조회 대상 블록 식별자로 블록 넘버, 블록 해시, 블록 태그 중
                    하나를 입력할 수 있습니다. 

                    3. `trace option`: trace 옵션 설정을 위한 object입니다.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              example:
                jsonrpc: '2.0'
                id: '1'
                result:
                  from: '0x0000000000000000000000000000000000000000'
                  gas: '0x2faf080'
                  gasUsed: '0x5d83'
                  to: '0xa3e0dfbf8dbd86e039f7cdb37682a776d66dae4b'
                  input: >-
                    0x70a08231000000000000000000000000a03167de1a56160e4647d77d81e9139af55b63d4
                  output: >-
                    0x000000000000000000000000000000000000000000000000000003c18cd105e2
                  value: '0x0'
                  type: CALL
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error_code
                properties:
                  message:
                    type: string
                  error_code:
                    type: string
                    description: >-
                      These codes provide more granular error information beyond
                      just the HTTP status code of the response.


                      Allowed values: account_not_found, resource_not_found,
                      module_not_found, struct_field_not_found,
                      version_not_found, transaction_not_found,
                      table_item_not_found, block_not_found,
                      state_value_not_found, version_pruned, block_pruned,
                      invalid_input, invalid_transaction_update,
                      sequence_number_too_old, vm_error, health_check_failed,
                      mempool_is_full, internal_error, web_framework_error,
                      bcs_not_supported, api_disabled
                  vm_error_code:
                    type: integer
                    description: >-
                      A code providing VM error details when submitting
                      transactions to the VM.
