openapi: 3.1.0
info:
  title: evm-optimism-eth_getBlockReceipts
  version: 1.2.16
servers:
  - url: https://{optimism-network}.nodit.io
    variables:
      optimism-network:
        default: optimism-mainnet
        enum:
          - optimism-mainnet
          - optimism-sepolia
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: >-
        The default value, `nodit-demo`, is only for use in the developer
        documentation. For real applications or services, use the API key
        obtained from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - evm-optimism-eth_getBlockReceipts
      description: "ë¸”ë¡ í•´ì‹œë¥¼ ìž…ë ¥í•˜ì—¬ í•´ë‹¹ ë¸”ë¡ì˜ Receiptë¥¼ ì¡°íšŒí•©ë‹ˆë‹¤.\n\t\t\t\t\t\n\n> ðŸš§ ì‘ë‹µ ì‹œê°„ì´ ì˜¤ëž˜ ê±¸ë¦¬ì‹œë‚˜ìš”? ë¸”ë¡ ë‚´ íŠ¸ëžœìž­ì…˜ ìˆ˜ì— ë”°ë¼ ì‘ë‹µ ì‹œê°„ì´ ê¸¸ì–´ì§ˆ ìˆ˜ ìžˆìŠµë‹ˆë‹¤!\n>\n> eth_getBlockReceiptsëŠ” íŠ¹ì • ë¸”ë¡ì— í¬í•¨ëœ ëª¨ë“  íŠ¸ëžœìž­ì…˜ì˜ ì‹¤í–‰ ê²°ê³¼(receipts)ë¥¼ í•œ ë²ˆì— ì¡°íšŒí•©ë‹ˆë‹¤. ì´ë•Œ íŠ¸ëžœìž­ì…˜ ìˆ˜ê°€ ë§Žê±°ë‚˜ ì‹¤í–‰ ê²°ê³¼ê°€ ë³µìž¡í•œ ê²½ìš°, ì‘ë‹µ ì‹œê°„ì´ ì§€ì—°ë  ìˆ˜ ìžˆìŠµë‹ˆë‹¤.\n>\n> ë¹ ë¥¸ ì‘ë‹µì„ ì›í•˜ì‹ ë‹¤ë©´ ë‹¤ìŒ ê¶Œìž¥ì‚¬í•­ì„ ì°¸ê³ í•˜ì„¸ìš”:\n>\n> - íŠ¹ì • íŠ¸ëžœìž­ì…˜ë§Œ í•„ìš”í•œ ê²½ìš°, eth_getTransactionReceiptë¥¼ ì‚¬ìš©í•˜ì—¬ ì›í•˜ëŠ” íŠ¸ëžœìž­ì…˜ì˜ ì‹¤í–‰ ê²°ê³¼ë§Œ ê°œë³„ ì¡°íšŒí•˜ëŠ” ê²ƒì„ ê¶Œìž¥í•©ë‹ˆë‹¤.\n"
      summary: eth_getBlockReceipts
      operationId: optimism-eth_getBlockReceipts
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: eth_getBlockReceipts
                params:
                  type: array
                  items:
                    oneOf:
                      - title: Block Identifier
                        type: string
                        oneOf:
                          - title: Block Number
                            type: string
                            pattern: ^0[xX][0-9a-fA-F]+$
                            default: '0x1076B5A'
                            description: ë¸”ë¡ ë„˜ë²„ëŠ” ë¸”ë¡ì˜ ìˆœì„œë¥¼ ë‚˜íƒ€ë‚´ëŠ” ìˆ«ìžìž…ë‹ˆë‹¤. ë¸”ë¡ ë„˜ë²„ëŠ” 16ì§„ìˆ˜ ë¬¸ìžì—´ë¡œ í‘œí˜„ë©ë‹ˆë‹¤.
                          - title: Block Hash
                            type: string
                            pattern: ^0[xX][0-9a-fA-F]{64}
                            default: >-
                              0x39008d07edf93c03bb9d1cfc80598fcf63f441ec86e9de3733fa6a484980ca48
                            description: >-
                              ë¸”ë¡ í•´ì‹œëŠ” ë¸”ë¡ì˜ ê³ ìœ  ì‹ë³„ìžìž…ë‹ˆë‹¤. ë¸”ë¡ í•´ì‹œê°’ì€ 64ìžë¦¬ 16ì§„ìˆ˜ ë¬¸ìžì—´ë¡œ
                              í‘œí˜„ë©ë‹ˆë‹¤.
                          - title: Block Tag
                            type: string
                            pattern: ^(latest|earliest|pending|safe|finalized)$
                            default: latest
                            description: >-
                              ë¸”ë¡ íƒœê·¸ëŠ” ë‹¤ìŒ ì¤‘ í•˜ë‚˜ë¥¼ ì‚¬ìš©í•˜ì—¬ ë¸”ë¡ì„ ì§€ì •í•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤.

                              * `earliest`: ì²´ì¸ì—ì„œ ì‚¬ìš© ê°€ëŠ¥í•œ ê°€ìž¥ ì˜¤ëž˜ëœ ë¸”ë¡ì„ ë‚˜íƒ€ëƒ…ë‹ˆë‹¤.

                              * `finalized`: ìµœê·¼ì— í™•ì •ëœ ë¸”ë¡ì„ ë‚˜íƒ€ë‚´ë©°, ì´ëŠ” ë” ì´ìƒ ë³€ê²½ë  ìˆ˜ ì—†ëŠ”
                              ì•ˆì •ì ì¸ ìƒíƒœì˜ ë¸”ë¡ì„ ì˜ë¯¸í•©ë‹ˆë‹¤. ì´ ìš©ì–´ëŠ” ì£¼ë¡œ ì§€ë¶„ ì¦ëª…(PoS) ë¸”ë¡ì²´ì¸ì—ì„œ
                              ì‚¬ìš©ë˜ë©°, ë¸”ë¡ì´ ìµœì¢…ì ìœ¼ë¡œ í™•ì •ë˜ì—ˆìŒì„ ë‚˜íƒ€ëƒ…ë‹ˆë‹¤.

                              * `safe`: ë„¤íŠ¸ì›Œí¬ì— ì˜í•´ ì•ˆì „í•˜ê²Œ ê°„ì£¼ë˜ëŠ” ìµœê·¼ ë¸”ë¡ì„ ë‚˜íƒ€ëƒ…ë‹ˆë‹¤. 'ì•ˆì „'í•œ
                              ë¸”ë¡ì€ ë„¤íŠ¸ì›Œí¬ ìž¬ì¡°ì§(reorgs)ì˜ ìœ„í—˜ ì—†ì´ ì‹ ë¢°í•  ìˆ˜ ìžˆëŠ” ê²ƒìœ¼ë¡œ ê°„ì£¼ë©ë‹ˆë‹¤.

                              * `latest`: í˜„ìž¬ ì²´ì¸ì˜ ê°€ìž¥ ìµœê·¼ ë¸”ë¡ì„ ë‚˜íƒ€ë‚´ë©°, ì•„ì§ ìµœì¢… í™•ì •ë˜ì§€ ì•Šì•˜ì„
                              ìˆ˜ ìžˆì–´ ìž¬ì¡°ì§(reorgs)ë  ê°€ëŠ¥ì„±ì´ ìžˆìŠµë‹ˆë‹¤. ì´ëŠ” ì¼ë°˜ì ìœ¼ë¡œ ê°€ìž¥ ìµœì‹ ì˜ ìƒíƒœë¥¼
                              ì¡°íšŒí•  ë•Œ ì‚¬ìš©ë©ë‹ˆë‹¤.

                              * `pending`: ì•„ì§ ì±„êµ´ë˜ì§€ ì•Šì€, ë©”ëª¨ë¦¬ í’€ì— ìžˆëŠ” íŠ¸ëžœìž­ì…˜ë“¤ì„ í¬í•¨í•  ì˜ˆì •ì¸
                              ë‹¤ìŒ ë¸”ë¡ì„ ë‚˜íƒ€ëƒ…ë‹ˆë‹¤. ì´ëŠ” ì£¼ë¡œ ì˜ˆì •ëœ íŠ¸ëžœìž­ì…˜ë“¤ì˜ ìƒíƒœë¥¼ í™•ì¸í•  ë•Œ ì‚¬ìš©ë©ë‹ˆë‹¤.
                        default: '0x12C1A00'
                        description: >-
                          ë¸”ë¡ ì§€ì •ì„ ìœ„í•´ ë¸”ë¡ í•´ì‹œ, ë¸”ë¡ ë„˜ë²„, ë˜ëŠ” ë¸”ë¡ íƒœê·¸ ì¤‘ í•˜ë‚˜ë¥¼ ì‚¬ìš©í•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤.

                          * ë¸”ë¡ ë„˜ë²„: 16ì§„ìˆ˜ ë¬¸ìžì—´ (ex. "0x1") 

                          * ë¸”ë¡ í•´ì‹œ: 64ìžë¦¬ 16ì§„ìˆ˜ ë¬¸ìžì—´ (ex.
                          "0x39008d07edf93c03bb9d1cfc80598fcf63f441ec86e9de3733fa6a484980ca48")]

                          * ë¸”ë¡ íƒœê·¸: enum ë¬¸ìžì—´ (ex. "latest", "earliest",
                          "pending")
                  minItems: 1
                  maxItems: 1
                  default:
                    - latest
                  description: "ë‹¤ìŒ íŒŒë¼ë¯¸í„°ë“¤ì„ íƒ€ìž…ì— ë§žê²Œ ë°°ì—´ë¡œ ìž…ë ¥í•©ë‹ˆë‹¤.\n1. `block identifier` - ì¡°íšŒ ëŒ€ìƒ ë¸”ë¡ ì‹ë³„ìžë¡œ ë¸”ë¡ ë„˜ë²„, ë¸”ë¡ í•´ì‹œ, ë¸”ë¡ íƒœê·¸ ì¤‘ í•˜ë‚˜ë¥¼ ìž…ë ¥í•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤. \n\t- ë¸”ë¡ ë„˜ë²„: 16ì§„ìˆ˜ ë¬¸ìžì—´ (ex. \"0x1\")\n\t- ë¸”ë¡ í•´ì‹œ: 64ìžë¦¬ 16ì§„ìˆ˜ ë¬¸ìžì—´ (ex. \"0x39008d07edf93c03bb9d1cfc80598fcf63f441ec86e9de3733fa6a484980ca48\")]\n\t- ë¸”ë¡ íƒœê·¸: enum ë¬¸ìžì—´ (ex. \"latest\", \"earliest\", \"pending\")"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              example:
                jsonrpc: '2.0'
                id: 1
                result:
                  - blockHash: >-
                      0xf30beb3b775df15a6260eabffcb36829d5f9ced5a9c7ea2ca05be9164851d2a9
                    blockNumber: '0x1076fc6'
                    contractAddress: null
                    cumulativeGasUsed: '0x32b59'
                    effectiveGasPrice: '0x99a077c25'
                    from: '0xd99b5603addd1306b56e9fcc001ebe65956d1e31'
                    gasUsed: '0x32b59'
                    logs:
                      - address: '0x000000000022d473030f116ddee9f6b43ac78ba3'
                        topics:
                          - >-
                            0xc6a377bfc4eb120024a8ac08eef205be16b817020812c73223e81d1bdb9708ec
                          - >-
                            0x000000000000000000000000d99b5603addd1306b56e9fcc001ebe65956d1e31
                          - >-
                            0x0000000000000000000000000d58df0929b6baf8ed231f3fa672f0e5dcd665f7
                          - >-
                            0x000000000000000000000000ef1c6e67703c7bd7107eed8303fbe6ec2554bf6b
                        data: >-
                          0x000000000000000000000000ffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000648995c20000000000000000000000000000000000000000000000000000000000000000
                        blockNumber: '0x1076fc6'
                        transactionHash: >-
                          0xe9bb07a140494db1d6f0a02f95e0804e520db1fd80bc541d95d4711e20e76e20
                        transactionIndex: '0x0'
                        blockHash: >-
                          0xf30beb3b775df15a6260eabffcb36829d5f9ced5a9c7ea2ca05be9164851d2a9
                        logIndex: '0x0'
                        removed: false
                      - address: '0x0d58df0929b6baf8ed231f3fa672f0e5dcd665f7'
                        topics:
                          - >-
                            0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
                          - >-
                            0x000000000000000000000000d99b5603addd1306b56e9fcc001ebe65956d1e31
                          - >-
                            0x0000000000000000000000003bcfd7f139a4286a37aabff1cbde1447e90a6d57
                        data: >-
                          0x0000000000000000000000000000000000000000000000656357415e66f0de16
                        blockNumber: '0x1076fc6'
                        transactionHash: >-
                          0xe9bb07a140494db1d6f0a02f95e0804e520db1fd80bc541d95d4711e20e76e20
                        transactionIndex: '0x0'
                        blockHash: >-
                          0xf30beb3b775df15a6260eabffcb36829d5f9ced5a9c7ea2ca05be9164851d2a9
                        logIndex: '0x1'
                        removed: false
                    logsBloom: >-
                      0x00210000000000000000000080000000000000000000000020001000000000000000020000000000800000000000000002014000880000000000000000280000000000000000000000004008000000201800000000400800000000000008040200000000000000000000000000000000400000000000040000000010000000000000004020000000000000000000000000000000000000080000004000001000020800000000000000000000000000000400000000000000400000100000000000000002000000000000000000000000400000000000001000000002000000000010200000000000000000000000000000000000000000000000000080000400
                    status: '0x1'
                    to: '0xef1c6e67703c7bd7107eed8303fbe6ec2554bf6b'
                    transactionHash: >-
                      0xe9bb07a140494db1d6f0a02f95e0804e520db1fd80bc541d95d4711e20e76e20
                    transactionIndex: '0x0'
                    type: '0x2'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error_code
                properties:
                  message:
                    type: string
                  error_code:
                    type: string
                    description: >-
                      These codes provide more granular error information beyond
                      just the HTTP status code of the response.


                      Allowed values: account_not_found, resource_not_found,
                      module_not_found, struct_field_not_found,
                      version_not_found, transaction_not_found,
                      table_item_not_found, block_not_found,
                      state_value_not_found, version_pruned, block_pruned,
                      invalid_input, invalid_transaction_update,
                      sequence_number_too_old, vm_error, health_check_failed,
                      mempool_is_full, internal_error, web_framework_error,
                      bcs_not_supported, api_disabled
                  vm_error_code:
                    type: integer
                    description: >-
                      A code providing VM error details when submitting
                      transactions to the VM.
