openapi: 3.1.0
info:
  title: evm-kaia-klay_getBlockReceipts
  version: 1.2.6
servers:
  - url: https://{kaia-network}.nodit.io
    variables:
      kaia-network:
        default: kaia-mainnet
        enum:
          - kaia-mainnet
          - kaia-kairos
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: >-
        The default value, `nodit-demo`, is only for use in the developer
        documentation. For real applications or services, use the API key
        obtained from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - evm-kaia-klay_getBlockReceipts
      description: "ë¸”ë¡ í•´ì‹œë¥¼ ìž…ë ¥í•˜ì—¬ í•´ë‹¹ ë¸”ë¡ì˜ Receiptë¥¼ ì¡°íšŒí•©ë‹ˆë‹¤.\n\t\t\t\t\t\n\n> ðŸš§ ì‘ë‹µ ì‹œê°„ì´ ì˜¤ëž˜ ê±¸ë¦¬ë‚˜ìš”? ë¸”ë¡ ë²”ìœ„ì— ë”°ë¼ ì‘ë‹µ ì‹œê°„ì´ ê¸¸ì–´ì§ˆ ìˆ˜ ìžˆìŠµë‹ˆë‹¤!\n>\n> íŠ¹ì • ë¸”ë¡ì„ ì¡°íšŒí•  ë•Œ, í•´ë‹¹ ë¸”ë¡ì— í¬í•¨ëœ íŠ¸ëžœìž­ì…˜ì˜ ì–‘, íŠ¸ëžœìž­ì…˜ì˜ ì‹¤í–‰ ê²°ê³¼ ë“±ì— ë”°ë¼ ì‘ë‹µ ì‹œê°„ì´ ê¸¸ì–´ì§ˆ ìˆ˜ ìžˆìŠµë‹ˆë‹¤.\n> ë§Œì•½ ë¹ ë¥¸ ì‘ë‹µì„ ì›í•œë‹¤ë©´ eth_getTransactionReceiptë¥¼ ì‚¬ìš©í•˜ì—¬ ì›í•˜ëŠ” íŠ¸ëžœìž­ì…˜ì˜ ì‹¤í–‰ ê²°ê³¼ë§Œ ì¡°íšŒí•˜ì„¸ìš”.\n"
      summary: klay_getBlockReceipts
      operationId: kaia-klay_getBlockReceipts
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: klay_getBlockReceipts
                params:
                  type: array
                  items:
                    oneOf:
                      - title: Block Identifier
                        type: string
                        oneOf:
                          - title: Block Number
                            type: string
                            pattern: ^0[xX][0-9a-fA-F]+$
                            default: '0x1076B5A'
                            description: ë¸”ë¡ ë„˜ë²„ëŠ” ë¸”ë¡ì˜ ìˆœì„œë¥¼ ë‚˜íƒ€ë‚´ëŠ” ìˆ«ìžìž…ë‹ˆë‹¤. ë¸”ë¡ ë„˜ë²„ëŠ” 16ì§„ìˆ˜ ë¬¸ìžì—´ë¡œ í‘œí˜„ë©ë‹ˆë‹¤.
                          - title: Block Hash
                            type: string
                            pattern: ^0[xX][0-9a-fA-F]{64}
                            default: >-
                              0x39008d07edf93c03bb9d1cfc80598fcf63f441ec86e9de3733fa6a484980ca48
                            description: >-
                              ë¸”ë¡ í•´ì‹œëŠ” ë¸”ë¡ì˜ ê³ ìœ  ì‹ë³„ìžìž…ë‹ˆë‹¤. ë¸”ë¡ í•´ì‹œê°’ì€ 64ìžë¦¬ 16ì§„ìˆ˜ ë¬¸ìžì—´ë¡œ
                              í‘œí˜„ë©ë‹ˆë‹¤.
                          - title: Block Tag
                            type: string
                            pattern: ^(latest|earliest|pending|safe|finalized)$
                            default: latest
                            description: >-
                              ë¸”ë¡ íƒœê·¸ëŠ” ë‹¤ìŒ ì¤‘ í•˜ë‚˜ë¥¼ ì‚¬ìš©í•˜ì—¬ ë¸”ë¡ì„ ì§€ì •í•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤.

                              * `earliest`: ì²´ì¸ì—ì„œ ì‚¬ìš© ê°€ëŠ¥í•œ ê°€ìž¥ ì˜¤ëž˜ëœ ë¸”ë¡ì„ ë‚˜íƒ€ëƒ…ë‹ˆë‹¤.

                              * `latest`: í˜„ìž¬ ì²´ì¸ì˜ ê°€ìž¥ ìµœê·¼ ë¸”ë¡ì„ ë‚˜íƒ€ë‚´ë©°, ì•„ì§ ìµœì¢… í™•ì •ë˜ì§€ ì•Šì•˜ì„
                              ìˆ˜ ìžˆì–´ ìž¬ì¡°ì§(reorgs)ë  ê°€ëŠ¥ì„±ì´ ìžˆìŠµë‹ˆë‹¤. ì´ëŠ” ì¼ë°˜ì ìœ¼ë¡œ ê°€ìž¥ ìµœì‹ ì˜ ìƒíƒœë¥¼
                              ì¡°íšŒí•  ë•Œ ì‚¬ìš©ë©ë‹ˆë‹¤.

                              * `pending`: ì•„ì§ ì±„êµ´ë˜ì§€ ì•Šì€, ë©”ëª¨ë¦¬ í’€ì— ìžˆëŠ” íŠ¸ëžœìž­ì…˜ë“¤ì„ í¬í•¨í•  ì˜ˆì •ì¸
                              ë‹¤ìŒ ë¸”ë¡ì„ ë‚˜íƒ€ëƒ…ë‹ˆë‹¤. ì´ëŠ” ì£¼ë¡œ ì˜ˆì •ëœ íŠ¸ëžœìž­ì…˜ë“¤ì˜ ìƒíƒœë¥¼ í™•ì¸í•  ë•Œ ì‚¬ìš©ë©ë‹ˆë‹¤.
                        default: latest
                        description: >-
                          ë¸”ë¡ ì§€ì •ì„ ìœ„í•´ ë¸”ë¡ í•´ì‹œ, ë¸”ë¡ ë„˜ë²„, ë˜ëŠ” ë¸”ë¡ íƒœê·¸ ì¤‘ í•˜ë‚˜ë¥¼ ì‚¬ìš©í•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤.

                          * ë¸”ë¡ ë„˜ë²„: 16ì§„ìˆ˜ ë¬¸ìžì—´ (ex. "0x1") 

                          * ë¸”ë¡ í•´ì‹œ: 64ìžë¦¬ 16ì§„ìˆ˜ ë¬¸ìžì—´ (ex.
                          "0x39008d07edf93c03bb9d1cfc80598fcf63f441ec86e9de3733fa6a484980ca48")]

                          * ë¸”ë¡ íƒœê·¸: enum ë¬¸ìžì—´ (ex. "latest", "earliest",
                          "pending")
                  minItems: 1
                  maxItems: 1
                  default:
                    - latest
                  description: "ë‹¤ìŒ íŒŒë¼ë¯¸í„°ë“¤ì„ íƒ€ìž…ì— ë§žê²Œ ë°°ì—´ë¡œ ìž…ë ¥í•©ë‹ˆë‹¤.\n1. `block identifier` - ì¡°íšŒ ëŒ€ìƒ ë¸”ë¡ ì‹ë³„ìžë¡œ ë¸”ë¡ ë„˜ë²„, ë¸”ë¡ í•´ì‹œ, ë¸”ë¡ íƒœê·¸ ì¤‘ í•˜ë‚˜ë¥¼ ìž…ë ¥í•  ìˆ˜ ìžˆìŠµë‹ˆë‹¤. \n\t- ë¸”ë¡ ë„˜ë²„: 16ì§„ìˆ˜ ë¬¸ìžì—´ (ex. \"0x1\")\n\t- ë¸”ë¡ í•´ì‹œ: 64ìžë¦¬ 16ì§„ìˆ˜ ë¬¸ìžì—´ (ex. \"0x39008d07edf93c03bb9d1cfc80598fcf63f441ec86e9de3733fa6a484980ca48\")]\n\t- ë¸”ë¡ íƒœê·¸: enum ë¬¸ìžì—´ (ex. \"latest\", \"earliest\", \"pending\")"
      responses:
        '200':
          description: Successful Response
          content:
            application/json: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error_code
                properties:
                  message:
                    type: string
                  error_code:
                    type: string
                    description: >-
                      These codes provide more granular error information beyond
                      just the HTTP status code of the response.


                      Allowed values: account_not_found, resource_not_found,
                      module_not_found, struct_field_not_found,
                      version_not_found, transaction_not_found,
                      table_item_not_found, block_not_found,
                      state_value_not_found, version_pruned, block_pruned,
                      invalid_input, invalid_transaction_update,
                      sequence_number_too_old, vm_error, health_check_failed,
                      mempool_is_full, internal_error, web_framework_error,
                      bcs_not_supported, api_disabled
                  vm_error_code:
                    type: integer
                    description: >-
                      A code providing VM error details when submitting
                      transactions to the VM.
