openapi: 3.1.0
info:
  title: evm-kaia-net_version
  version: 1.2.10
servers:
  - url: https://{kaia-network}.nodit.io
    variables:
      kaia-network:
        default: kaia-mainnet
        enum:
          - kaia-mainnet
          - kaia-kairos
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: >-
        The default value, `nodit-demo`, is only for use in the developer
        documentation. For real applications or services, use the API key
        obtained from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - evm-kaia-net_version
      description: >-
        연결된 Ethereum 네트워크의 네트워크 ID를 반환합니다. 네트워크 ID는 Ethereum의 다양한 네트워크(예: 메인넷,
        테스트넷 등)를 구분하는 데 사용됩니다. 예를 들어, Ethereum 메인넷의 네트워크 ID는 1이고, Ropsten 테스트넷은
        3, Rinkeby 테스트넷은 4입니다. 이 메소드는 주로 네트워크를 식별하고, 애플리케이션이 올바른 네트워크에 연결되어 있는지
        확인하는 데 사용됩니다.
      summary: net_version
      operationId: kaia-net_version
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: net_version
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              example:
                jsonrpc: '2.0'
                id: 1
                result: '1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error_code
                properties:
                  message:
                    type: string
                  error_code:
                    type: string
                    description: >-
                      These codes provide more granular error information beyond
                      just the HTTP status code of the response.


                      Allowed values: account_not_found, resource_not_found,
                      module_not_found, struct_field_not_found,
                      version_not_found, transaction_not_found,
                      table_item_not_found, block_not_found,
                      state_value_not_found, version_pruned, block_pruned,
                      invalid_input, invalid_transaction_update,
                      sequence_number_too_old, vm_error, health_check_failed,
                      mempool_is_full, internal_error, web_framework_error,
                      bcs_not_supported, api_disabled
                  vm_error_code:
                    type: integer
                    description: >-
                      A code providing VM error details when submitting
                      transactions to the VM.
