openapi: 3.1.0
info:
  title: evm-polygon-bor_getCurrentValidators
  version: 1.2.6
servers:
  - url: https://{polygon-network}.nodit.io
    variables:
      polygon-network:
        default: polygon-mainnet
        enum:
          - polygon-mainnet
          - polygon-amoy
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: >-
        The default value, `nodit-demo`, is only for use in the developer
        documentation. For real applications or services, use the API key
        obtained from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - evm-polygon-bor_getCurrentValidators
      description: >-
        현재 네트워크에서 활성화된 검증자의 목록을 반환합니다. 이 메소드는 네트워크의 현재 검증자들을 식별하는 데 사용되며, 네트워크의
        거버넌스와 보안 상태를 이해하는 데 중요한 정보를 제공합니다. 검증자 목록은 네트워크의 합의 프로토콜과 거버넌스 메커니즘에 따라
        변경될 수 있으며, 이 메소드를 통해 현재 활성화된 검증자들을 조회할 수 있습니다.
      summary: bor_getCurrentValidators
      operationId: polygon-bor_getCurrentValidators
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: bor_getCurrentValidators
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              example:
                jsonrpc: '2.0'
                id: 1
                result:
                  - ID: 0
                    signer: '0x00856730088a5c3191bd26eb482e45229555ce57'
                    power: 1
                    accum: -26
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error_code
                properties:
                  message:
                    type: string
                  error_code:
                    type: string
                    description: >-
                      These codes provide more granular error information beyond
                      just the HTTP status code of the response.


                      Allowed values: account_not_found, resource_not_found,
                      module_not_found, struct_field_not_found,
                      version_not_found, transaction_not_found,
                      table_item_not_found, block_not_found,
                      state_value_not_found, version_pruned, block_pruned,
                      invalid_input, invalid_transaction_update,
                      sequence_number_too_old, vm_error, health_check_failed,
                      mempool_is_full, internal_error, web_framework_error,
                      bcs_not_supported, api_disabled
                  vm_error_code:
                    type: integer
                    description: >-
                      A code providing VM error details when submitting
                      transactions to the VM.
