openapi: 3.1.0
info:
  title: Hippo - cosmos_mint_v1beta1_params
  version: 1.0.0
servers:
  - url: https://rest-hippo-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /cosmos/mint/v1beta1/params:
    get:
      description: Params returns the total set of minting parameters.
      operationId: cosmos_mint_v1beta1_params
      tags:
        - mint
      responses:
        "200":
          description: Successful Response
          content:
            "*/*":
              schema:
                type: object
                properties:
                  params:
                    description: params defines the parameters of the module.
                    type: object
                    properties:
                      mint_denom:
                        type: string
                        title: type of coin to mint
                      inflation_rate_change:
                        type: string
                        title: maximum annual change in inflation rate
                      inflation_max:
                        type: string
                        title: maximum inflation rate
                      inflation_min:
                        type: string
                        title: minimum inflation rate
                      goal_bonded:
                        type: string
                        title: goal of percent bonded atoms
                      blocks_per_year:
                        type: string
                        format: uint64
                        title: expected blocks per year
                description: QueryParamsResponse is the response type for the Query/Params RPC method.
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      security:
        - api_key: []
      summary: /cosmos/mint/v1beta1/params
