openapi: 3.1.0
info:
  title: Hippo - cosmos_distribution_v1beta1_params
  version: 1.0.0
servers:
  - url: https://rest-hippo-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /cosmos/distribution/v1beta1/params:
    get:
      description: Params queries params of the distribution module.
      operationId: cosmos_distribution_v1beta1_params
      tags:
        - distribution
      responses:
        "200":
          description: Successful Response
          content:
            "*/*":
              schema:
                type: object
                properties:
                  params:
                    description: params defines the parameters of the module.
                    type: object
                    properties:
                      community_tax:
                        type: string
                      base_proposer_reward:
                        type: string
                        description: |-
                          Deprecated: The base_proposer_reward field is deprecated and is no longer used
                          in the x/distribution module's reward mechanism.
                      bonus_proposer_reward:
                        type: string
                        description: |-
                          Deprecated: The bonus_proposer_reward field is deprecated and is no longer used
                          in the x/distribution module's reward mechanism.
                      withdraw_addr_enabled:
                        type: boolean
                description: QueryParamsResponse is the response type for the Query/Params RPC method.
        default:
          description: An unexpected error response.
          content:
            "*/*":
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        type_url:
                          type: string
                        value:
                          type: string
                          format: byte
      security:
        - api_key: []
      summary: /cosmos/distribution/v1beta1/params
