openapi: 3.1.0
info:
  title: Injective - BroadCastTxSync
  version: 1.0.0
servers:
  - url: https://rpc-injective-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /:
    post:
      security:
        - api_key: []
      operationId: broadcast_tx_sync
      summary: BroadCastTxSync
      description: Broadcasts a transaction synchronously and returns the CheckTx result. Does not wait for the DeliverTx result.
      tags:
        - json-rpc-api
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - jsonrpc
                - id
                - method
              properties:
                jsonrpc:
                  type: string
                  const: "2.0"
                id:
                  type: integer
                method:
                  type: string
                  const: broadcast_tx_sync
                params:
                  type: object
                  additionalProperties: false
                  required:
                    - tx
                  properties:
                    tx:
                      type: string
                      description: Encoded transaction.
            example:
              jsonrpc: "2.0"
              id: 1
              method: broadcast_tx_sync
              params:
                tx: a/encoded_tx/c
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - jsonrpc
                  - id
                  - result
                properties:
                  jsonrpc:
                    type: string
                    const: "2.0"
                  id:
                    type: integer
                  error:
                    type: string
                  result:
                    type: object
                    additionalProperties: false
                    properties:
                      code:
                        type: string
                      data:
                        type: string
                      log:
                        type: string
                      codespace:
                        type: string
                      hash:
                        type: string
              example:
                jsonrpc: "2.0"
                id: 1
                result:
                  code: "0"
                  data: ""
                  log: "[]"
                  codespace: ""
                  hash: D70952032620CC4E2737EB8AC379806359D8E0B17B0488F627997A0B043ABDED
