openapi: 3.1.0
info:
  title: sui_getNormalizedMoveStruct
  version: 1.2.10
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        description: The network to use for the API.
        enum:
          - sui-mainnet
        default: sui-mainnet
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - sui_getNormalizedMoveStruct
      description: |
        Return a structured representation of Move struct
      summary: sui_getNormalizedMoveStruct
      operationId: sui-sui_getNormalizedMoveStruct
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: sui_getNormalizedMoveStruct
                params:
                  type: array
                  minItems: 3
                  maxItems: 3
                  items:
                    oneOf:
                      - title: package
                        $ref: '#/components/schemas/ObjectID'
                        description: The package ID
                      - title: module_name
                        type: string
                        description: The module name
                      - title: struct_name
                        type: string
                        description: The struct name
              example:
                jsonrpc: '2.0'
                id: 1
                method: sui_getNormalizedMoveStruct
                params:
                  - '0xc95b9e341bc3aba1654bdbad707dcd773bd6309363447ef3fe58a960de92aa93'
                  - module
                  - StructName
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    $ref: '#/components/schemas/SuiMoveNormalizedStruct'
              example:
                jsonrpc: '2.0'
                result:
                  abilities:
                    abilities:
                      - Store
                      - Key
                  typeParameters: []
                  fields: []
                id: 1
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: The default value, `nodit-demo`, is only for use in the developer documentation. For real applications or services, use the API key obtained from the Nodit console.
  schemas:
    Hex:
      description: Hex string encoding.
      type: string
    ObjectID:
      allOf:
        - $ref: '#/components/schemas/Hex'
    SuiMoveAbility:
      type: string
      enum:
        - Copy
        - Drop
        - Store
        - Key
    SuiMoveAbilitySet:
      type: object
      required:
        - abilities
      properties:
        abilities:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveAbility'
    SuiMoveNormalizedType:
      oneOf:
        - type: string
          enum:
            - Bool
            - U8
            - U16
            - U32
            - U64
            - U128
            - U256
            - Address
            - Signer
        - type: object
          required:
            - Struct
          properties:
            Struct:
              type: object
              required:
                - address
                - module
                - name
                - typeArguments
              properties:
                address:
                  type: string
                module:
                  type: string
                name:
                  type: string
                typeArguments:
                  type: array
                  items:
                    $ref: '#/components/schemas/SuiMoveNormalizedType'
          additionalProperties: false
        - type: object
          required:
            - Vector
          properties:
            Vector:
              $ref: '#/components/schemas/SuiMoveNormalizedType'
          additionalProperties: false
        - type: object
          required:
            - TypeParameter
          properties:
            TypeParameter:
              type: integer
              format: uint16
              minimum: 0
          additionalProperties: false
        - type: object
          required:
            - Reference
          properties:
            Reference:
              $ref: '#/components/schemas/SuiMoveNormalizedType'
          additionalProperties: false
        - type: object
          required:
            - MutableReference
          properties:
            MutableReference:
              $ref: '#/components/schemas/SuiMoveNormalizedType'
          additionalProperties: false
    SuiMoveNormalizedField:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/SuiMoveNormalizedType'
    SuiMoveStructTypeParameter:
      type: object
      required:
        - constraints
        - isPhantom
      properties:
        constraints:
          $ref: '#/components/schemas/SuiMoveAbilitySet'
        isPhantom:
          type: boolean
    SuiMoveNormalizedStruct:
      type: object
      required:
        - abilities
        - fields
        - typeParameters
      properties:
        abilities:
          $ref: '#/components/schemas/SuiMoveAbilitySet'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveNormalizedField'
        typeParameters:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveStructTypeParameter'
    Base58:
      type: string
    Digest:
      allOf:
        - $ref: '#/components/schemas/Base58'
      description: A representation of a 32 byte digest
    BigInt_for_uint64:
      type: string
    Error:
      type: object
      properties:
        code:
          type: string
          description: Returns a code that identifies the situation where the error occurred.
        message:
          type: string
          description: Returns a detailed message explaining the cause of the error.
      required:
        - code
        - message
  responses:
    '400':
      description: Unauthorized
      content:
        application/json:
          schema:
            oneOf:
              - type: object
                properties:
                  code:
                    type: string
                    enum:
                      - notExists
                  object_id:
                    $ref: '#/components/schemas/ObjectID'
              - type: object
                properties:
                  code:
                    type: string
                    enum:
                      - dynamic_field_not_found
                  parent_object_id:
                    $ref: '#/components/schemas/ObjectID'
              - type: object
                properties:
                  code:
                    type: string
                    enum:
                      - deleted
                  digest:
                    $ref: '#/components/schemas/Digest'
                  object_id:
                    $ref: '#/components/schemas/ObjectID'
                  version:
                    $ref: '#/components/schemas/BigInt_for_uint64'
              - type: object
                required:
                  - code
                properties:
                  code:
                    type: string
                    enum:
                      - unknown
              - type: object
                required:
                  - code
                  - error
                properties:
                  code:
                    type: string
                    enum:
                      - displayError
                  error:
                    type: string
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: AUTHENTICATION_FAILED
              message: Authentication failed
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: PERMISSION_DENIED
              message: Permission denied
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: RESOURCE_NOT_FOUND
              message: 'Resource not found: { RESOURCE1_NAME = RESOURCE1_VALUE, RESOURCE2_NAME = RESOURCE2_VALUE, ... }'
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: TOO_MANY_REQUESTS
              message: Too many requests
