openapi: 3.1.0
info:
  title: sui_getNormalizedMoveModulesByPackage
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        description: The network to use for the API.
        enum:
          - sui-mainnet
        default: sui-mainnet
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - sui_getNormalizedMoveModulesByPackage
      description: |
        Return structured representations of all modules in the given package
      summary: sui_getNormalizedMoveModulesByPackage
      operationId: sui-sui_getNormalizedMoveModulesByPackage
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: sui_getNormalizedMoveModulesByPackage
                params:
                  type: array
                  minItems: 1
                  maxItems: 1
                  items:
                    oneOf:
                      - title: package
                        $ref: '#/components/schemas/ObjectID'
                        description: The package ID
              example:
                jsonrpc: '2.0'
                id: 1
                method: sui_getNormalizedMoveModulesByPackage
                params:
                  - '0x61630d3505f8905a0f4d42c6ff39a78a6ba2b28f68a3299ec3417bbabc6717dc'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    type: object
                    additionalProperties:
                      $ref: '#/components/schemas/SuiMoveNormalizedModule'
              example:
                jsonrpc: '2.0'
                result:
                  fileFormatVersion: 6
                  address: '0x800105867da4655eca6d9eb1258bfd1ad92af329a07781ee71e60065e00f2de9'
                  name: module
                  friends: []
                  structs: {}
                  exposedFunctions: {}
                id: 1
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: The default value, `nodit-demo`, is only for use in the developer documentation. For real applications or services, use the API key obtained from the Nodit console.
  schemas:
    Hex:
      description: Hex string encoding.
      type: string
    ObjectID:
      allOf:
        - $ref: '#/components/schemas/Hex'
    SuiMoveAbility:
      type: string
      enum:
        - Copy
        - Drop
        - Store
        - Key
    SuiMoveAbilitySet:
      type: object
      required:
        - abilities
      properties:
        abilities:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveAbility'
    SuiMoveStructTypeParameter:
      type: object
      required:
        - constraints
        - isPhantom
      properties:
        constraints:
          $ref: '#/components/schemas/SuiMoveAbilitySet'
        isPhantom:
          type: boolean
    SuiMoveNormalizedType:
      oneOf:
        - type: string
          enum:
            - Bool
            - U8
            - U16
            - U32
            - U64
            - U128
            - U256
            - Address
            - Signer
        - type: object
          required:
            - Struct
          properties:
            Struct:
              type: object
              required:
                - address
                - module
                - name
                - typeArguments
              properties:
                address:
                  type: string
                module:
                  type: string
                name:
                  type: string
                typeArguments:
                  type: array
                  items:
                    $ref: '#/components/schemas/SuiMoveNormalizedType'
          additionalProperties: false
        - type: object
          required:
            - Vector
          properties:
            Vector:
              $ref: '#/components/schemas/SuiMoveNormalizedType'
          additionalProperties: false
        - type: object
          required:
            - TypeParameter
          properties:
            TypeParameter:
              type: integer
              format: uint16
              minimum: 0
          additionalProperties: false
        - type: object
          required:
            - Reference
          properties:
            Reference:
              $ref: '#/components/schemas/SuiMoveNormalizedType'
          additionalProperties: false
        - type: object
          required:
            - MutableReference
          properties:
            MutableReference:
              $ref: '#/components/schemas/SuiMoveNormalizedType'
          additionalProperties: false
    SuiMoveNormalizedField:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/SuiMoveNormalizedType'
    SuiMoveNormalizedEnum:
      type: object
      required:
        - abilities
        - typeParameters
        - variants
      properties:
        abilities:
          $ref: '#/components/schemas/SuiMoveAbilitySet'
        typeParameters:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveStructTypeParameter'
        variantDeclarationOrder:
          type:
            - array
            - 'null'
          items:
            type: string
        variants:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/SuiMoveNormalizedField'
    SuiMoveVisibility:
      type: string
      enum:
        - Private
        - Public
        - Friend
    SuiMoveNormalizedFunction:
      type: object
      required:
        - isEntry
        - parameters
        - return
        - typeParameters
        - visibility
      properties:
        isEntry:
          type: boolean
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveNormalizedType'
        return:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveNormalizedType'
        typeParameters:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveAbilitySet'
        visibility:
          $ref: '#/components/schemas/SuiMoveVisibility'
    SuiMoveModuleId:
      type: object
      required:
        - address
        - name
      properties:
        address:
          type: string
        name:
          type: string
    SuiMoveNormalizedStruct:
      type: object
      required:
        - abilities
        - fields
        - typeParameters
      properties:
        abilities:
          $ref: '#/components/schemas/SuiMoveAbilitySet'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveNormalizedField'
        typeParameters:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveStructTypeParameter'
    SuiMoveNormalizedModule:
      type: object
      required:
        - address
        - exposedFunctions
        - fileFormatVersion
        - friends
        - name
        - structs
      properties:
        address:
          type: string
        enums:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SuiMoveNormalizedEnum'
        exposedFunctions:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SuiMoveNormalizedFunction'
        fileFormatVersion:
          type: integer
          format: uint32
          minimum: 0
        friends:
          type: array
          items:
            $ref: '#/components/schemas/SuiMoveModuleId'
        name:
          type: string
        structs:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SuiMoveNormalizedStruct'
    Base58:
      type: string
    Digest:
      allOf:
        - $ref: '#/components/schemas/Base58'
      description: A representation of a 32 byte digest
    BigInt_for_uint64:
      type: string
    ObjectResponseError:
      oneOf:
        - type: object
          required:
            - code
            - object_id
          properties:
            code:
              type: string
              enum:
                - notExists
            object_id:
              $ref: '#/components/schemas/ObjectID'
        - type: object
          required:
            - code
            - parent_object_id
          properties:
            code:
              type: string
              enum:
                - dynamicFieldNotFound
            parent_object_id:
              $ref: '#/components/schemas/ObjectID'
        - type: object
          required:
            - code
            - digest
            - object_id
            - version
          properties:
            code:
              type: string
              enum:
                - deleted
            digest:
              description: Base64 string representing the object digest
              allOf:
                - $ref: '#/components/schemas/Digest'
            object_id:
              $ref: '#/components/schemas/ObjectID'
            version:
              description: Object version.
              allOf:
                - $ref: '#/components/schemas/BigInt_for_uint64'
        - type: object
          required:
            - code
          properties:
            code:
              type: string
              enum:
                - unknown
        - type: object
          required:
            - code
            - error
          properties:
            code:
              type: string
              enum:
                - displayError
            error:
              type: string
    Error:
      type: object
      properties:
        code:
          type: string
          description: Returns a code that identifies the situation where the error occurred.
        message:
          type: string
          description: Returns a detailed message explaining the cause of the error.
      required:
        - code
        - message
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
                description: JSON-RPC version
                example: '2.0'
              id:
                type: integer
                description: Request ID
                example: 1
              error:
                $ref: '#/components/schemas/ObjectResponseError'
            required:
              - jsonrpc
              - id
              - error
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: AUTHENTICATION_FAILED
              message: Authentication failed
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: PERMISSION_DENIED
              message: Permission denied
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: RESOURCE_NOT_FOUND
              message: 'Resource not found: { RESOURCE1_NAME = RESOURCE1_VALUE, RESOURCE2_NAME = RESOURCE2_VALUE, ... }'
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: TOO_MANY_REQUESTS
              message: Too many requests
