openapi: 3.1.0
info:
  title: SUI Node API
  version: 1.2.10
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        description: The network to use for the API.
        enum:
          - sui-mainnet
        default: sui-mainnet
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - suix_getAllCoins
      description: |
        Return all Coin objects owned by an address.
      summary: suix_getAllCoins
      operationId: suix_getAllCoins
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: suix_getAllCoins
                params:
                  type: array
                  minItems: 1
                  maxItems: 3
                  items:
                    oneOf:
                      - title: owner
                        $ref: '#/components/schemas/SuiAddress'
                        description: The owner's Sui address
                      - title: cursor
                        type: string
                        description: Optional paging cursor
                      - title: limit
                        type: integer
                        description: Maximum number of items per page
              example:
                jsonrpc: '2.0'
                id: 1
                method: suix_getAllCoins
                params:
                  - '0x41f5975e3c6bd5c95f041a8493ad7e9934be26e69152d2c2e86d8a9bdbd242b3'
                  - '0x2564cd31a71cf9833609b111436d8f0f47b7f8b9927ec3f8975a1dcbf9b25564'
                  - 3
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  jsonrpc:
                    type: string
                  result:
                    $ref: '#/components/schemas/Page_for_Coin_and_String'
              example:
                jsonrpc: '2.0'
                result:
                  data:
                    - coinType: 0x2::sui::SUI
                      coinObjectId: '0x861c5e055605b2bb1199faf653a8771e448930bc95a0369fad43a9870a2e5878'
                      version: '103626'
                      digest: Ao1QyN9UTmYzb2ead3D5xhSBk7TvACRvmnJW8gRbwP99
                      balance: '200000000'
                      previousTransaction: 7dp5WtTmtGp83EXYYFMzjBJRFeSgR67AzqMETLrfgeFx
                    - coinType: 0x2::sui::SUI
                      coinObjectId: '0x7e769678d059761bff8a8f3944642e4c33a6e4fb0b55f8face36fadaa22f2a0d'
                      version: '103626'
                      digest: 5taVxHU9QLQD5cNdqxt8kNGAab93GMG4vX7zYDxEaohx
                      balance: '200000000'
                      previousTransaction: 9xLdMXezY8d1yRA2TtN6pYjapyy2EVKHWNriGPFGCFvd
                    - coinType: 0x2::sui::SUI
                      coinObjectId: '0xa323d541ba5cf9e34919d2644cda38a263f69f47ae954dec65295231e0d2c7c8'
                      version: '103626'
                      digest: 82ZNKSSueWUQkpFNbBZGHSr3sUL5Rxfr7ucVRsvgQzz2
                      balance: '200000000'
                      previousTransaction: 5xexWFq6QpGHBQyC9P2cbAJXq9qm2EjzfuRM9NwS1uyG
                  nextCursor: abcd
                  hasNextPage: true
                id: 1
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: The default value, `nodit-demo`, is only for use in the developer documentation. For real applications or services, use the API key obtained from the Nodit console.
  schemas:
    Hex:
      description: Hex string encoding.
      type: string
    SuiAddress:
      allOf:
        - $ref: '#/components/schemas/Hex'
    BigInt_for_uint64:
      type: string
    ObjectID:
      allOf:
        - $ref: '#/components/schemas/Hex'
    Base58:
      type: string
    Digest:
      allOf:
        - $ref: '#/components/schemas/Base58'
      description: A representation of a 32 byte digest
    TransactionDigest:
      allOf:
        - $ref: '#/components/schemas/Digest'
      description: A transaction will have a (unique) digest.
    SequenceNumber:
      type: integer
      format: uint64
      minimum: 0
    Coin:
      type: object
      required:
        - balance
        - coinObjectId
        - coinType
        - digest
        - previousTransaction
        - version
      properties:
        balance:
          $ref: '#/components/schemas/BigInt_for_uint64'
        coinObjectId:
          $ref: '#/components/schemas/ObjectID'
        coinType:
          type: string
        digest:
          $ref: '#/components/schemas/Digest'
        previousTransaction:
          $ref: '#/components/schemas/TransactionDigest'
        version:
          $ref: '#/components/schemas/SequenceNumber'
    Page_for_Coin_and_String:
      description: '`next_cursor` points to the last item in the page; Reading with `next_cursor` will start from the next item after `next_cursor` if `next_cursor` is `Some`, otherwise it will start from the first item.'
      type: object
      required:
        - data
        - hasNextPage
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Coin'
        hasNextPage:
          type: boolean
        nextCursor:
          type:
            - string
            - 'null'
    Error:
      type: object
      properties:
        code:
          type: string
          description: Returns a code that identifies the situation where the error occurred.
        message:
          type: string
          description: Returns a detailed message explaining the cause of the error.
      required:
        - code
        - message
  responses:
    '400':
      description: Unauthorized
      content:
        application/json:
          schema:
            oneOf:
              - type: object
                properties:
                  code:
                    type: string
                    enum:
                      - notExists
                  object_id:
                    $ref: '#/components/schemas/ObjectID'
              - type: object
                properties:
                  code:
                    type: string
                    enum:
                      - dynamic_field_not_found
                  parent_object_id:
                    $ref: '#/components/schemas/ObjectID'
              - type: object
                properties:
                  code:
                    type: string
                    enum:
                      - deleted
                  digest:
                    $ref: '#/components/schemas/Digest'
                  object_id:
                    $ref: '#/components/schemas/ObjectID'
                  version:
                    $ref: '#/components/schemas/BigInt_for_uint64'
              - type: object
                required:
                  - code
                properties:
                  code:
                    type: string
                    enum:
                      - unknown
              - type: object
                required:
                  - code
                  - error
                properties:
                  code:
                    type: string
                    enum:
                      - displayError
                  error:
                    type: string
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: AUTHENTICATION_FAILED
              message: Authentication failed
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: PERMISSION_DENIED
              message: Permission denied
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: RESOURCE_NOT_FOUND
              message: 'Resource not found: { RESOURCE1_NAME = RESOURCE1_VALUE, RESOURCE2_NAME = RESOURCE2_VALUE, ... }'
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: TOO_MANY_REQUESTS
              message: Too many requests
