openapi: 3.1.0
info:
  title: suix_resolveNameServiceNames
  version: 1.2.17
servers:
  - url: https://{sui-network}.nodit.io
    variables:
      sui-network:
        description: The network to use for the API.
        enum:
          - sui-mainnet
        default: sui-mainnet
paths:
  /:
    post:
      security:
        - api_key: []
      tags:
        - suix_resolveNameServiceNames
      description: |
        Return the resolved names given address, if multiple names are resolved, the first one is the primary name.
      summary: suix_resolveNameServiceNames
      operationId: sui-suix_resolveNameServiceNames
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - jsonrpc
                - method
                - params
              properties:
                id:
                  type: integer
                  default: 1
                jsonrpc:
                  type: string
                  default: '2.0'
                method:
                  type: string
                  default: suix_resolveNameServiceNames
                params:
                  type: array
                  minItems: 1
                  maxItems: 3
                  items:
                    oneOf:
                      - title: address
                        $ref: '#/components/schemas/SuiAddress'
                        description: The address to resolve
                      - title: cursor
                        $ref: '#/components/schemas/ObjectID'
                        description: Optional paging cursor
                      - title: limit
                        type: integer
                        description: Maximum number of items per page
              example:
                jsonrpc: '2.0'
                id: 1
                method: suix_resolveNameServiceNames
                params:
                  - '0x5cd6fa76ed1d18f05f15e35075252ddec4fb83621d55952d9172fcfcb72feae2'
                  - '0xd22bbb46f892c42d9ec0ae4de93e02c75973a51c17180798237326a58694a2cf'
                  - 3
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: integer
                  result:
                    $ref: '#/components/schemas/Page_for_String_and_ObjectID'
              example:
                jsonrpc: '2.0'
                result:
                  data:
                    - example.sui
                  nextCursor: '0xd22bbb46f892c42d9ec0ae4de93e02c75973a51c17180798237326a58694a2cf'
                  hasNextPage: false
                id: 1
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: The default value, `nodit-demo`, is only for use in the developer documentation. For real applications or services, use the API key obtained from the Nodit console.
  schemas:
    Hex:
      description: Hex string encoding.
      type: string
    SuiAddress:
      allOf:
        - $ref: '#/components/schemas/Hex'
    ObjectID:
      allOf:
        - $ref: '#/components/schemas/Hex'
    Page_for_String_and_ObjectID:
      description: '`next_cursor` points to the last item in the page; Reading with `next_cursor` will start from the next item after `next_cursor` if `next_cursor` is `Some`, otherwise it will start from the first item.'
      type: object
      required:
        - data
        - hasNextPage
      properties:
        data:
          type: array
          items:
            type: string
        hasNextPage:
          type: boolean
        nextCursor:
          $ref: '#/components/schemas/ObjectID'
    Base58:
      type: string
    Digest:
      allOf:
        - $ref: '#/components/schemas/Base58'
      description: A representation of a 32 byte digest
    BigInt_for_uint64:
      type: string
    ObjectResponseError:
      oneOf:
        - type: object
          required:
            - code
            - object_id
          properties:
            code:
              type: string
              enum:
                - notExists
            object_id:
              $ref: '#/components/schemas/ObjectID'
        - type: object
          required:
            - code
            - parent_object_id
          properties:
            code:
              type: string
              enum:
                - dynamicFieldNotFound
            parent_object_id:
              $ref: '#/components/schemas/ObjectID'
        - type: object
          required:
            - code
            - digest
            - object_id
            - version
          properties:
            code:
              type: string
              enum:
                - deleted
            digest:
              description: Base64 string representing the object digest
              allOf:
                - $ref: '#/components/schemas/Digest'
            object_id:
              $ref: '#/components/schemas/ObjectID'
            version:
              description: Object version.
              allOf:
                - $ref: '#/components/schemas/BigInt_for_uint64'
        - type: object
          required:
            - code
          properties:
            code:
              type: string
              enum:
                - unknown
        - type: object
          required:
            - code
            - error
          properties:
            code:
              type: string
              enum:
                - displayError
            error:
              type: string
    Error:
      type: object
      properties:
        code:
          type: string
          description: Returns a code that identifies the situation where the error occurred.
        message:
          type: string
          description: Returns a detailed message explaining the cause of the error.
      required:
        - code
        - message
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
                description: JSON-RPC version
                example: '2.0'
              id:
                type: integer
                description: Request ID
                example: 1
              error:
                $ref: '#/components/schemas/ObjectResponseError'
            required:
              - jsonrpc
              - id
              - error
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: AUTHENTICATION_FAILED
              message: Authentication failed
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: PERMISSION_DENIED
              message: Permission denied
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: RESOURCE_NOT_FOUND
              message: 'Resource not found: { RESOURCE1_NAME = RESOURCE1_VALUE, RESOURCE2_NAME = RESOURCE2_VALUE, ... }'
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            example:
              code: TOO_MANY_REQUESTS
              message: Too many requests
