openapi: 3.1.0
info:
  title: Initia - UnconfirmedTxs
  version: 1.0.0
servers:
  - url: https://rpc-initia-mainnet.nodit.io
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      x-default: nodit-demo
      description: |
        The example value `nodit-demo` is for use in the developer documentation only.
        For real applications or services, please use the API key issued from the Nodit console.
paths:
  /unconfirmed_txs:
    get:
      security:
        - api_key: []
      operationId: unconfirmed_txs
      summary: UnconfirmedTxs
      description: Retrieves the list of unconfirmed transactions.
      tags:
        - rest-api
      parameters:
        - name: limit
          in: query
          description: Maximum number of transactions to return.
          schema:
            type: string
          example: "20"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - jsonrpc
                  - id
                  - result
                properties:
                  jsonrpc:
                    type: string
                    const: "2.0"
                  id:
                    type: integer
                  result:
                    type: object
                    additionalProperties: false
                    properties:
                      n_txs:
                        type: string
                      total:
                        type: string
                      total_bytes:
                        type: string
                      txs:
                        type: array
                        items:
                          type: string
              example:
                jsonrpc: "2.0"
                id: 1
                result:
                  n_txs: "2"
                  total: "2"
                  total_bytes: "1024"
                  txs:
                    - a/encoded_tx_1/c
                    - a/encoded_tx_2/c
